// Generated by scripts/build-component.mjs from the component WIT. Do not edit.

import type * as Worker from './interfaces/pydantic-monty-worker.js'

export * from './interfaces/pydantic-monty-worker.js'

export interface ComponentExports {
  'pydantic:monty/worker': typeof Worker
  worker: typeof Worker
}

/** Instantiates the generated component wrapper and its core modules. */
export function instantiate(
  getCoreModule: (path: string) => WebAssembly.Module | Promise<WebAssembly.Module>,
  imports: Record<string, unknown>,
): ComponentExports | Promise<ComponentExports>
