/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Runs Python code and returns the result as a string.
 *
 * The code is executed in a sandboxed environment with no resource limits.
 * Print statements are captured and returned along with the final result.
 *
 * # Arguments
 * * `code` - The Python code to execute
 *
 * # Returns
 * A `RunResult` containing the printed output and the result of the last expression.
 *
 * # Errors
 * Returns an error if the code fails to parse or encounters a runtime error.
 */
export declare function run(code: string): RunResult

/** Result of running Python code. */
export interface RunResult {
  /** Any output from print statements during execution. */
  output: string
  /** The debug representation of the final result. */
  result: string
}
