use std::{
    cell::{Cell, UnsafeCell},
    collections::hash_map::DefaultHasher,
    hash::{Hash, Hasher},
    marker::PhantomData,
    mem::{ManuallyDrop, discriminant, size_of},
    ptr::NonNull,
    vec,
};

use bytemuck::TransparentWrapper;
use smallvec::SmallVec;

// Re-export items moved to `heap_traits` so that `crate::heap::HeapGuard` etc. continue
// to resolve (used by the `defer_drop!` macros and throughout the codebase).
pub(crate) use crate::heap_data::HeapData;
pub(crate) use crate::heap_traits::{ContainsHeap, DropWithHeap, HeapGuard, ImmutableHeapGuard};
use crate::{
    asyncio::{Coroutine, GatherFuture, GatherItem},
    exception_private::{ExcType, RunResult, SimpleException},
    heap_data::{CellValue, Closure, FunctionDefaults},
    intern::Interns,
    resource::{ResourceError, ResourceTracker, check_mult_size, check_repeat_size},
    types::{
        Bytes, Dataclass, Dict, DictItemsView, DictKeysView, DictValuesView, FrozenSet, List, LongInt, Module,
        MontyIter, NamedTuple, Path, PyTrait, Range, ReMatch, RePattern, Set, Slice, Str, Tuple, allocate_tuple,
    },
    value::Value,
};

/// Unique identifier for values stored inside the heap arena.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub struct HeapId(usize);

impl HeapId {
    /// Returns the raw index value.
    #[inline]
    pub fn index(self) -> usize {
        self.0
    }
}

/// The empty tuple is a singleton which is allocated at startup.
const EMPTY_TUPLE_ID: HeapId = HeapId(0);

/// Hash caching state stored alongside each heap entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
enum HashState {
    /// Hash has not yet been computed but the value might be hashable.
    Unknown,
    /// Cached hash value for immutable types that have been hashed at least once.
    Cached(u64),
    /// Value is unhashable (mutable types or tuples containing unhashables).
    Unhashable,
}

impl HashState {
    fn for_data(data: &HeapData) -> Self {
        match data {
            // Cells are hashable by identity (like all Python objects without __hash__ override)
            // FrozenSet is immutable and hashable
            // Range is immutable and hashable
            // Slice is immutable and hashable (like in CPython)
            // LongInt is immutable and hashable
            // NamedTuple is immutable and hashable (like Tuple)
            HeapData::Str(_)
            | HeapData::Bytes(_)
            | HeapData::Tuple(_)
            | HeapData::NamedTuple(_)
            | HeapData::FrozenSet(_)
            | HeapData::Cell(_)
            | HeapData::Closure(_)
            | HeapData::FunctionDefaults(_)
            | HeapData::Range(_)
            | HeapData::Slice(_)
            | HeapData::LongInt(_) => Self::Unknown,
            // Dataclass hashability depends on the mutable flag
            HeapData::Dataclass(dc) => {
                if dc.is_frozen() {
                    Self::Unknown
                } else {
                    Self::Unhashable
                }
            }
            // Path is immutable and hashable
            HeapData::Path(_) => Self::Unknown,
            // ExtFunction is hashable (by identity, like closures)
            HeapData::ExtFunction(_) => Self::Unknown,
            // other types are unhashable
            _ => Self::Unhashable,
        }
    }
}

/// This structure allows for reading into the heap more efficiently than repeated calls to `Heap::get` and
/// `Heap::get_mut` by performing the indexing and type lookup once, and then using the borrow checker to
/// safely deference the resulting pointers for short-lived borrows.
///
/// The safety boundary is primarily that `HeapRead` pointers generated by the `HeapReader::read` API must remain valid
/// for their lifetime, see the safety notes in `HeapRead::get` for how that is guaranteed.
pub(crate) struct HeapReader<'a, T: ResourceTracker> {
    pub(crate) heap: &'a mut Heap<T>,
    /// Makes the lifetime `'a` invariant.
    phantom: PhantomData<fn(&'a T) -> &'a T>,
}

impl<T: ResourceTracker> HeapReader<'_, T> {
    /// The ONLY way to get a `HeapReader`. By only providing an API which takes a closure which
    /// must be satisfied for all `'a`, it's impossible to create other `HeapReader` with the
    /// exact same lifetime `'a`.
    pub fn with<R>(heap: &mut Heap<T>, f: impl for<'a> FnOnce(&'a mut HeapReader<'a, T>) -> R) -> R {
        f(&mut HeapReader {
            heap: &mut *heap,
            phantom: PhantomData,
        })
    }
}

impl<'a, T: ResourceTracker> HeapReader<'a, T> {
    /// Indexes into the heap
    pub fn read(&mut self, id: HeapId) -> HeapReadOutput<'a> {
        /// Computes a `HeapRead` from the raw `UnsafeCell` pointer and a shared reference
        /// to the variant field. The `&T` is only used to compute the field's byte offset
        /// within the `HeapData` enum; the returned `NonNull` is derived from the original
        /// `*mut HeapData` pointer so it inherits the `SharedReadWrite` permission from
        /// the `UnsafeCell`, allowing both reads and writes.
        #[inline]
        fn heap_read<'a, T>(base: *mut HeapData, field: &T, readers: NonNull<Cell<usize>>) -> HeapRead<'a, T> {
            let base_addr = base as usize;
            let field_addr = std::ptr::from_ref(field) as usize;
            let offset = field_addr - base_addr;
            HeapRead {
                // SAFETY: The pointer is derived from the UnsafeCell's `*mut` via byte
                // offset, preserving the `SharedReadWrite` permission. No reference retag
                // occurs — we only use the `&T` for its address, not to derive the pointer.
                value: unsafe { NonNull::new_unchecked(base.byte_add(offset).cast::<T>()) },
                readers,
                borrow: PhantomData,
            }
        }

        /// Like `heap_read` but for `Box<T>` fields inside `HeapData` variants.
        ///
        /// For boxed variants, the `Box`'s heap allocation lives at a separate
        /// address from the `HeapData` enum, so the offset-from-base trick used
        /// by `heap_read` doesn't work. Instead we derive the pointer directly
        /// from the `Box`'s inner allocation. The pointer remains valid for the
        /// `HeapReader`'s lifetime because the `HeapData` (and its `Box`) stay
        /// alive as long as the reader exists.
        #[expect(
            clippy::borrowed_box,
            reason = "We intentionally take &Box<T> to signal this is for boxed HeapData variants; &T would lose that context"
        )]
        fn heap_read_boxed<'a, T>(boxed: &Box<T>, readers: NonNull<Cell<usize>>) -> HeapRead<'a, T> {
            HeapRead {
                // SAFETY: The Box's allocation is valid for reads/writes as long as the
                // HeapData containing it is alive. The HeapReader guarantees the entry
                // won't be deallocated. We cast away the shared reference to get a mutable
                // pointer — this is sound because all mutation goes through `get_mut` which
                // requires `&mut HeapReader`, ensuring exclusive access.
                value: unsafe { NonNull::new_unchecked(std::ptr::from_ref(boxed.as_ref()).cast_mut()) },
                readers,
                borrow: PhantomData,
            }
        }

        let heap = self.heap.heap_mut();
        let entry = heap
            .entries
            .get(id.index())
            .expect("HeapReader::read: object already freed");

        // Increment the reader count for this entry. The corresponding decrement
        // happens in `HeapRead::drop`.
        entry.readers.set(entry.readers.get() + 1);
        let readers = NonNull::from(&entry.readers);

        // Get the raw pointer from the UnsafeCell — this has SharedReadWrite permission.
        let base: *mut HeapData = entry.data.0.get();

        // SAFETY: Match on a shared reference (`&*base`) to read the discriminant without
        // creating a Unique retag. The shared retag is compatible with existing
        // SharedReadWrite permissions from prior `read()` calls into the same UnsafeCell.
        // The `heap_read` helper then derives the NonNull from `base` (not from `&T`),
        // so the returned pointer retains full SharedReadWrite permission.
        match unsafe { &*base } {
            HeapData::Str(s) => HeapReadOutput::Str(heap_read(base, s, readers)),
            HeapData::Bytes(bytes) => HeapReadOutput::Bytes(heap_read(base, bytes, readers)),
            HeapData::List(list) => HeapReadOutput::List(heap_read(base, list, readers)),
            HeapData::Tuple(tuple) => HeapReadOutput::Tuple(heap_read(base, tuple, readers)),
            HeapData::NamedTuple(named_tuple) => HeapReadOutput::NamedTuple(heap_read(base, named_tuple, readers)),
            HeapData::Dict(dict) => HeapReadOutput::Dict(heap_read(base, dict, readers)),
            HeapData::DictItemsView(v) => HeapReadOutput::DictItemsView(heap_read(base, v, readers)),
            HeapData::DictKeysView(v) => HeapReadOutput::DictKeysView(heap_read(base, v, readers)),
            HeapData::DictValuesView(v) => HeapReadOutput::DictValuesView(heap_read(base, v, readers)),
            HeapData::Set(set) => HeapReadOutput::Set(heap_read(base, set, readers)),
            HeapData::FrozenSet(frozen_set) => HeapReadOutput::FrozenSet(heap_read(base, frozen_set, readers)),
            HeapData::Closure(closure) => HeapReadOutput::Closure(heap_read(base, closure, readers)),
            HeapData::FunctionDefaults(function_defaults) => {
                HeapReadOutput::FunctionDefaults(heap_read(base, function_defaults, readers))
            }
            HeapData::ExtFunction(name) => HeapReadOutput::ExtFunction(heap_read(base, name, readers)),
            HeapData::Cell(cell_value) => HeapReadOutput::Cell(heap_read(base, cell_value, readers)),
            HeapData::Range(range) => HeapReadOutput::Range(heap_read(base, range, readers)),
            HeapData::Slice(slice) => HeapReadOutput::Slice(heap_read(base, slice, readers)),
            HeapData::Exception(simple_exception) => {
                HeapReadOutput::Exception(heap_read(base, simple_exception, readers))
            }
            HeapData::Dataclass(dataclass) => HeapReadOutput::Dataclass(heap_read(base, dataclass, readers)),
            HeapData::Iter(monty_iter) => HeapReadOutput::Iter(heap_read(base, monty_iter, readers)),
            HeapData::LongInt(l) => HeapReadOutput::LongInt(heap_read(base, l, readers)),
            HeapData::Module(module) => HeapReadOutput::Module(heap_read(base, module, readers)),
            HeapData::Coroutine(coroutine) => HeapReadOutput::Coroutine(heap_read(base, coroutine, readers)),
            HeapData::GatherFuture(gather_future) => {
                HeapReadOutput::GatherFuture(heap_read(base, gather_future, readers))
            }
            HeapData::Path(path) => HeapReadOutput::Path(heap_read(base, path, readers)),
            HeapData::RePattern(re_pattern) => HeapReadOutput::RePattern(heap_read_boxed(re_pattern, readers)),
            HeapData::ReMatch(re_match) => HeapReadOutput::ReMatch(heap_read(base, re_match, readers)),
        }
    }
}

impl<T: ResourceTracker> ContainsHeap for HeapReader<'_, T> {
    type ResourceTracker = T;

    fn heap(&self) -> &Heap<T> {
        self.heap.heap()
    }
    fn heap_mut(&mut self) -> &mut Heap<T> {
        self.heap.heap_mut()
    }
}

impl<T: ResourceTracker> std::ops::Deref for HeapReader<'_, T> {
    type Target = Heap<T>;

    fn deref(&self) -> &Self::Target {
        self.heap
    }
}

impl<T: ResourceTracker> std::ops::DerefMut for HeapReader<'_, T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.heap
    }
}

pub enum HeapReadOutput<'a> {
    Str(HeapRead<'a, Str>),
    Bytes(HeapRead<'a, Bytes>),
    List(HeapRead<'a, List>),
    Tuple(HeapRead<'a, Tuple>),
    NamedTuple(HeapRead<'a, NamedTuple>),
    Dict(HeapRead<'a, Dict>),
    DictItemsView(HeapRead<'a, DictItemsView>),
    DictKeysView(HeapRead<'a, DictKeysView>),
    DictValuesView(HeapRead<'a, DictValuesView>),
    Set(HeapRead<'a, Set>),
    FrozenSet(HeapRead<'a, FrozenSet>),
    Closure(HeapRead<'a, Closure>),
    FunctionDefaults(HeapRead<'a, FunctionDefaults>),
    ExtFunction(HeapRead<'a, String>),
    Cell(HeapRead<'a, CellValue>),
    Range(HeapRead<'a, Range>),
    Slice(HeapRead<'a, Slice>),
    Exception(HeapRead<'a, SimpleException>),
    Dataclass(HeapRead<'a, Dataclass>),
    Iter(HeapRead<'a, MontyIter>),
    LongInt(HeapRead<'a, LongInt>),
    Module(HeapRead<'a, Module>),
    Coroutine(HeapRead<'a, Coroutine>),
    GatherFuture(HeapRead<'a, GatherFuture>),
    Path(HeapRead<'a, Path>),
    RePattern(HeapRead<'a, RePattern>),
    ReMatch(HeapRead<'a, ReMatch>),
}

pub struct HeapRead<'a, T: ?Sized> {
    value: NonNull<T>,
    /// Pointer to the `readers` counter in the owning `HeapValue`.
    ///
    /// Incremented on creation, decremented on drop. This ensures `dec_ref`
    /// cannot free the entry while any `HeapRead` pointing into it exists.
    readers: NonNull<Cell<usize>>,
    /// Makes the lifetime `'a` invariant. In combination with the invariant lifetime
    /// on `HeapReader` and the `HeapReader::with` API, this guarantees that this
    /// `HeapRead` originated from that matching `HeapReader` (there is no way to
    /// construct another `HeapReader` with the same lifetime).
    borrow: PhantomData<fn(&'a T) -> &'a T>,
}

impl<T: ?Sized> Drop for HeapRead<'_, T> {
    fn drop(&mut self) {
        // SAFETY: (DH) the readers pointer is valid for the lifetime of the HeapValue,
        // which is guaranteed by the paged storage (addresses never move) and the
        // reader count itself (dec_ref cannot free an entry with active readers).
        let cell = unsafe { self.readers.as_ref() };
        cell.set(cell.get() - 1);
    }
}

impl<'a, T: ?Sized> HeapRead<'a, T> {
    /// Accesses the value contained in this reference.
    pub fn get<'r, RT: ResourceTracker>(&self, _: &'r HeapReader<'a, RT>) -> &'r T {
        // SAFETY: (DH)
        //  - The HeapReader has an invariant lifetime 'a which guarantees that this HeapRead
        //    came from the heap borrowed by this HeapReader.
        //  - The address of the `HeapValue` never changes because entries are stored in
        //    paged storage (`PagedEntries`) where each page is a `Box<[Option<HeapValue>]>`
        //    that is never reallocated or moved.
        //  - The HeapRead holds a strong reader reference (via the `readers` counter in
        //    `HeapValue`) which guarantees the entry will never be freed by `dec_ref`
        //    while this `HeapRead` exists.
        //  - The type of the `HeapValue` can never change once allocated. This is
        //    guaranteed by never exposing `&mut HeapData` outside of this module.
        //  - The borrow on `HeapReader` guarantees that there are no mutable borrows on any heap
        //    data while the return value of this function is alive.
        unsafe { self.value.as_ref() }
    }

    /// Mutably accesses the value contained in this reference.
    pub fn get_mut<'r>(&mut self, _: &'r mut HeapReader<'a, impl ResourceTracker>) -> &'r mut T {
        // SAFETY: see same constraints as in get() above.
        unsafe { self.value.as_mut() }
    }

    /// Cast this reader around some type T which is a transparent wrapper around U
    /// to its inner type. Name peel comes from `TransparentWrapper::peel` method.
    ///
    /// Transfers ownership of the reader count from `self` to the returned `HeapRead`
    /// (no net increment/decrement).
    #[expect(dead_code)]
    pub fn peel<U>(self) -> HeapRead<'a, U>
    where
        T: TransparentWrapper<U>,
    {
        // Wrap in `ManuallyDrop` to avoid dropping `self` - transferring ownerhship of `readers`
        let this = ManuallyDrop::new(self);
        HeapRead {
            // NB this pointer casting is safe because `T` is a transparent wrapper around `U`,
            // this means all the safety protections listed in `.get` about accessing `T` also
            // apply to `U`.
            value: NonNull::cast(this.value),
            readers: this.readers,
            borrow: PhantomData,
        }
    }

    /// Casts this reader to a field of type `U` at some `offset` within the struct.
    ///
    /// Transfers ownership of the reader count from `self` to the returned `HeapRead`.
    ///
    /// # Safety
    ///   - The field of type `U` must ALWAYS exist at `offset` within `T` (i.e. `T` cannot be an enum, union etc)
    unsafe fn cast_as_member<U>(self, offset: usize) -> HeapRead<'a, U> {
        let this = ManuallyDrop::new(self);
        HeapRead {
            // SAFETY: (DH) - caller of this function guarantees the offset & cast is valid
            value: unsafe { this.value.byte_add(offset) }.cast(),
            readers: this.readers,
            borrow: PhantomData,
        }
    }
}

/// Unsafe helper for `heap_read_as_field`, do not use. Same safety invariants as `HeapRead::cast_as_member`.
pub(crate) unsafe fn cast_as_member_type_hinted<'a, T, U>(
    heap_read: HeapRead<'a, T>,
    offset: usize,
    _type_hint: impl for<'s> Fn(&'s HeapRead<'a, T>) -> *const U,
) -> HeapRead<'a, U> {
    // SAFETY: (DH) - caller upholds `cast_as_member` contract
    unsafe { heap_read.cast_as_member(offset) }
}

macro_rules! heap_read_as_field {
    ($heap_read:ident, $ty:ty, $field:ident) => {{
        let offset = std::mem::offset_of!($ty, $field);
        #[expect(unreachable_code)]
        let type_hint = |read: &$crate::heap::HeapRead<'_, $ty>| {
            &raw const read.get::<$crate::NoLimitTracker>(unreachable!()).$field
        };
        // SAFETY: (DH)
        //  - `std::mem::offset_of!` guarantees there is a field at fixed offset
        //  - `type_hint` guarantees that the field is of type `U` for the safety contract
        unsafe { $crate::heap::cast_as_member_type_hinted($heap_read, offset, type_hint) }
    }};
}

pub(crate) use heap_read_as_field;

/// A single entry inside the heap arena, storing refcount, payload, and hash metadata.
///
/// The `hash_state` field tracks whether the heap entry is hashable and, if so,
/// caches the computed hash. Mutable types (List, Dict) start as `Unhashable` and
/// will raise TypeError if used as dict keys.
///
/// The `data` field is an Option to support temporary borrowing: when methods like
/// `with_entry_mut` or `call_attr` need mutable access to both the data and the heap,
/// they can `.take()` the data out (leaving `None`), pass `&mut Heap` to user code,
/// then restore the data. This avoids unsafe code while keeping `refcount` accessible
/// for `inc_ref`/`dec_ref` during the borrow.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct HeapValue {
    refcount: Cell<usize>,
    /// Number of active `HeapRead` pointers into this entry's data.
    ///
    /// Incremented when `HeapReader::read` creates a `HeapRead`, decremented when
    /// the `HeapRead` is dropped. `dec_ref` panics if it would free an entry that
    /// still has active readers — this guarantees that `HeapRead` pointers remain
    /// valid for as long as they exist.
    #[serde(skip, default)] // should always be 0 during serde ops
    readers: Cell<usize>,
    /// The payload data
    data: UnsafeHeapData,
    /// Current hashing status / cached hash value
    hash_state: HashState,
}

/// This wrapper containing `UnsafeCell` exists to allow for data inside of `HeapValue`
/// to be safely pointed to via the `HeapReader` API.
///
/// The safety invariants are protected by the `Heap` / `HeapReader` API:
///   - It is never possible to alias mutable and immutable borrows into heap values,
///     whether they are the same or different value.
///   - When a mutable borrow of a heap value exists, no other heap value may be
///     borrowed. (See `Heap::get_mut` and `HeapRead::get`, which both require a `&mut`
///     borrow on the heap.)
#[derive(Debug)]
struct UnsafeHeapData(UnsafeCell<HeapData>);

impl serde::Serialize for UnsafeHeapData {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        // SAFETY: when heap data is being serialized, there is no mutable borrow
        // possible on any data contents
        HeapData::serialize(unsafe { &*self.0.get() }, serializer)
    }
}

impl<'de> serde::Deserialize<'de> for UnsafeHeapData {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        Ok(Self(UnsafeCell::new(HeapData::deserialize(deserializer)?)))
    }
}

/// Number of entries per page in the paged heap storage.
///
/// Each page is a `Box<[Option<HeapValue>]>` that is never moved once allocated.
/// This guarantees that pointers into entries (used by `HeapRead`) remain valid
/// even as the heap grows and new pages are appended.
const PAGE_SIZE: usize = 256;

/// Paged storage for heap entries that guarantees address stability.
///
/// Entries are stored in fixed-size pages (`Box<[Option<HeapValue>]>`).
/// Once a page is allocated, it is never reallocated or moved in memory.
/// This is the key invariant that makes `HeapRead` pointers safe: a `NonNull<T>`
/// derived from an entry's data will remain valid for the entry's entire lifetime.
///
/// Index `i` maps to `pages[i / PAGE_SIZE][i % PAGE_SIZE]`.
#[derive(Debug)]
struct PagedEntries {
    pages: Vec<Box<[Option<HeapValue>]>>,
    /// Total number of slots (including freed ones). Always equals
    /// `pages.len() * PAGE_SIZE` rounded down to the actual number of pushed entries.
    len: usize,
}

impl PagedEntries {
    fn new() -> Self {
        Self {
            pages: Vec::new(),
            len: 0,
        }
    }

    /// Returns the total number of slots (including freed/None ones).
    #[inline]
    fn len(&self) -> usize {
        self.len
    }

    /// Returns a shared reference to the entry at `index`.
    ///
    /// # Panics
    /// Panics if `index >= len`.
    #[inline]
    fn get(&self, index: usize) -> Option<&HeapValue> {
        assert!(
            index < self.len,
            "PagedEntries::get: index {index} out of bounds (len={})",
            self.len
        );
        self.pages[index / PAGE_SIZE][index % PAGE_SIZE].as_ref()
    }

    /// Returns a mutable reference to the entry at `index`.
    ///
    /// # Panics
    /// Panics if `index >= len`.
    #[inline]
    fn get_mut(&mut self, index: usize) -> &mut Option<HeapValue> {
        assert!(
            index < self.len,
            "PagedEntries::get_mut: index {index} out of bounds (len={})",
            self.len
        );
        &mut self.pages[index / PAGE_SIZE][index % PAGE_SIZE]
    }

    /// Appends a new entry and returns its index.
    fn push(&mut self, value: Option<HeapValue>) -> usize {
        let index = self.len;
        let page_idx = index / PAGE_SIZE;
        let slot_idx = index % PAGE_SIZE;

        if page_idx >= self.pages.len() {
            // Allocate a new page filled with None
            let mut page = Vec::new();
            page.resize_with(PAGE_SIZE, || None);
            self.pages.push(page.into_boxed_slice());
        }

        self.pages[page_idx][slot_idx] = value;
        self.len += 1;
        index
    }

    /// Returns a mutable reference to the entry at `index`, or `None` if out of bounds.
    #[inline]
    fn try_get_mut(&mut self, index: usize) -> Option<&mut Option<HeapValue>> {
        if index < self.len {
            Some(&mut self.pages[index / PAGE_SIZE][index % PAGE_SIZE])
        } else {
            None
        }
    }

    /// Iterates over all entries as shared references.
    fn iter(&self) -> impl Iterator<Item = &Option<HeapValue>> {
        self.pages.iter().flat_map(|page| page.iter()).take(self.len)
    }

    /// Iterates over all entries as mutable references.
    fn iter_mut(&mut self) -> impl Iterator<Item = &mut Option<HeapValue>> {
        let len = self.len;
        self.pages.iter_mut().flat_map(|page| page.iter_mut()).take(len)
    }
}

impl serde::Serialize for PagedEntries {
    /// Serializes as a flat `Vec<Option<HeapValue>>` for compatibility.
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeSeq;
        let mut seq = serializer.serialize_seq(Some(self.len))?;
        for entry in self.iter() {
            seq.serialize_element(entry)?;
        }
        seq.end()
    }
}

impl<'de> serde::Deserialize<'de> for PagedEntries {
    /// Deserializes from a flat `Vec<Option<HeapValue>>` and repacks into pages.
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let flat: Vec<Option<HeapValue>> = Vec::deserialize(deserializer)?;
        let mut paged = Self::new();
        for entry in flat {
            paged.push(entry);
        }
        Ok(paged)
    }
}

/// Zero-size token returned by [`Heap::incr_recursion_depth`].
///
/// Represents one level of recursion depth that must be released when the
/// recursive operation completes. There are two ways to release the token:
///
/// - **`DropWithHeap`** — for `&mut Heap` paths (e.g., `py_eq`). Compatible with
///   `defer_drop!` and `HeapGuard` for automatic cleanup on all code paths.
/// - **`DropWithImmutableHeap`** — for `&Heap` paths (e.g., `py_repr_fmt`) where
///   only shared access is available. Compatible with `defer_drop_immutable_heap!`
///   and `ImmutableHeapGuard`.
#[derive(Debug)]
pub(crate) struct RecursionToken(());

impl DropWithHeap for RecursionToken {
    #[inline]
    fn drop_with_heap<H: ContainsHeap>(self, heap: &mut H) {
        heap.heap().decr_recursion_depth();
    }
}

/// Reference-counted arena that backs all heap-only runtime values.
///
/// Uses a free list to reuse slots from freed values, keeping memory usage
/// constant for long-running loops that repeatedly allocate and free values.
/// When an value is freed via `dec_ref`, its slot ID is added to the free list.
/// New allocations pop from the free list when available, otherwise append.
///
/// Generic over `T: ResourceTracker` to support different resource tracking strategies.
/// When `T = NoLimitTracker` (the default), all resource checks compile away to no-ops.
///
/// Serialization requires `T: Serialize` and `T: Deserialize`. Custom serde implementation
/// handles the Drop constraint by using `std::mem::take` during serialization.
#[derive(Debug)]
pub(crate) struct Heap<T: ResourceTracker> {
    entries: PagedEntries,
    /// IDs of freed slots available for reuse. Populated by `dec_ref`, consumed by `allocate`.
    free_list: Vec<HeapId>,
    /// Resource tracker for enforcing limits and scheduling GC.
    tracker: T,
    /// True if reference cycles may exist. Set when a container stores a Ref,
    /// cleared after GC completes. When false, GC can skip mark-sweep entirely.
    may_have_cycles: bool,
    /// Number of GC applicable allocations since the last GC.
    allocations_since_gc: u32,
    /// Current recursion depth — incremented on function calls and data structure traversals.
    ///
    /// Uses `Cell` for interior mutability so that methods with only `&Heap`
    /// (like `py_repr_fmt`) can still increment/decrement the depth counter.
    recursion_depth: Cell<usize>,
}

impl<T: ResourceTracker + serde::Serialize> serde::Serialize for Heap<T> {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut state = serializer.serialize_struct("Heap", 6)?;
        state.serialize_field("entries", &self.entries)?;
        state.serialize_field("free_list", &self.free_list)?;
        state.serialize_field("tracker", &self.tracker)?;
        state.serialize_field("may_have_cycles", &self.may_have_cycles)?;
        state.serialize_field("allocations_since_gc", &self.allocations_since_gc)?;
        state.end()
    }
}

impl<'de, T: ResourceTracker + serde::Deserialize<'de>> serde::Deserialize<'de> for Heap<T> {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(serde::Deserialize)]
        struct HeapFields<T> {
            entries: PagedEntries,
            free_list: Vec<HeapId>,
            tracker: T,
            may_have_cycles: bool,
            allocations_since_gc: u32,
        }
        let fields = HeapFields::<T>::deserialize(deserializer)?;
        Ok(Self {
            entries: fields.entries,
            free_list: fields.free_list,
            tracker: fields.tracker,
            may_have_cycles: fields.may_have_cycles,
            allocations_since_gc: fields.allocations_since_gc,
            recursion_depth: Cell::new(0),
        })
    }
}

/// GC interval - run GC every 100,000 applicable allocations.
///
/// This is intentionally infrequent to minimize overhead while still
/// eventually collecting reference cycles.
const GC_INTERVAL: u32 = 100_000;

impl<T: ResourceTracker> Heap<T> {
    /// Creates a new heap with the given resource tracker.
    ///
    /// Use this to create heaps with custom resource limits or GC scheduling.
    pub fn new(_capacity: usize, tracker: T) -> Self {
        let mut this = Self {
            entries: PagedEntries::new(),
            free_list: Vec::new(),
            tracker,
            may_have_cycles: false,
            allocations_since_gc: 0,
            recursion_depth: Cell::new(0),
        };
        // TBC: should the empty tuple contribute to the resource limits?
        // If not, can just place it in `entries` directly without going through `allocate()`.
        let empty_tuple = this
            .allocate(HeapData::Tuple(Tuple::default()))
            .expect("Failed to allocate empty tuple singleton");
        debug_assert_eq!(empty_tuple, EMPTY_TUPLE_ID);
        this
    }

    /// Returns a reference to the resource tracker.
    pub fn tracker(&self) -> &T {
        &self.tracker
    }

    /// Returns a mutable reference to the resource tracker.
    pub fn tracker_mut(&mut self) -> &mut T {
        &mut self.tracker
    }

    /// Checks whether the configured time limit has been exceeded.
    ///
    /// Delegates to the resource tracker's `check_time()`. For `NoLimitTracker`,
    /// this is inlined as a no-op with zero runtime cost. For `LimitTracker`,
    /// it compares elapsed time against the configured `max_duration_secs`.
    ///
    /// Call this inside Rust-side loops (builtins, sort, iterator collection)
    /// that execute within a single bytecode instruction and would otherwise
    /// bypass the VM's per-instruction timeout check.
    #[inline]
    pub fn check_time(&self) -> Result<(), ResourceError> {
        self.tracker.check_time()
    }

    /// Increments the recursion depth and checks the limit via the `ResourceTracker`.
    ///
    /// Returns `Ok(RecursionToken)` if within limits. The caller must ensure the
    /// token is released on all code paths — either via `defer_drop!`/`HeapGuard`
    /// (for `&mut Heap` contexts) or via `RecursionToken::release()` (for `&Heap` contexts).
    ///
    /// Returns `Err(ResourceError::Recursion)` if the limit would be exceeded.
    #[inline]
    pub fn incr_recursion_depth(&self) -> Result<RecursionToken, ResourceError> {
        let depth = self.recursion_depth.get();
        self.tracker.check_recursion_depth(depth)?;
        self.recursion_depth.set(depth + 1);
        Ok(RecursionToken(()))
    }

    /// Increments the recursion depth, returning `Some(RecursionToken)` if within
    /// limits, or `None` if the limit is exceeded.
    ///
    /// Use this in repr-like contexts where exceeding the limit should produce
    /// truncated output (e.g., `[...]`) rather than an error.
    #[inline]
    pub fn incr_recursion_depth_for_repr(&self) -> Option<RecursionToken> {
        self.incr_recursion_depth().ok()
    }

    /// Decrements the recursion depth.
    ///
    /// Called internally by `RecursionToken` — prefer releasing the token
    /// rather than calling this directly.
    #[inline]
    pub(crate) fn decr_recursion_depth(&self) {
        let depth = self.recursion_depth.get();
        debug_assert!(depth > 0, "decr_recursion_depth called when depth is 0");
        self.recursion_depth.set(depth - 1);
    }

    /// Returns the current recursion depth.
    ///
    /// Used during async task switching to compute a task's depth contribution
    /// before adjusting the global counter.
    pub(crate) fn get_recursion_depth(&self) -> usize {
        self.recursion_depth.get()
    }

    /// Sets the recursion depth to an explicit value.
    ///
    /// Used after deserialization to restore the recursion depth to match
    /// the number of active (non-global) namespace frames that were serialized.
    /// Also used during async task switching to subtract/add a task's depth
    /// contribution when switching away from/to that task.
    pub(crate) fn set_recursion_depth(&self, depth: usize) {
        self.recursion_depth.set(depth);
    }

    /// Number of entries in the heap
    pub fn size(&self) -> usize {
        self.entries.len()
    }

    /// Marks that a reference cycle may exist in the heap.
    ///
    /// Call this when a container (list, dict, tuple, etc.) stores a reference
    /// to another heap object. This enables the GC to skip mark-sweep entirely
    /// when no cycles are possible.
    #[inline]
    pub fn mark_potential_cycle(&mut self) {
        self.may_have_cycles = true;
    }

    /// Returns the number of GC-tracked allocations since the last garbage collection.
    ///
    /// This counter increments for each allocation of a GC-tracked type (List, Dict, etc.)
    /// and resets to 0 when `collect_garbage` runs. Useful for testing GC behavior.
    #[cfg(feature = "ref-count-return")]
    pub fn get_allocations_since_gc(&self) -> u32 {
        self.allocations_since_gc
    }

    /// Allocates a new heap entry.
    ///
    /// Returns `Err(ResourceError)` if allocation would exceed configured limits.
    /// Use this when you need to handle resource limit errors gracefully.
    ///
    /// Only GC-tracked types (containers that can hold references) count toward the
    /// GC allocation threshold. Leaf types like strings don't trigger GC.
    ///
    /// When allocating a container that contains heap references, marks potential
    /// cycles to enable garbage collection.
    pub fn allocate(&mut self, data: HeapData) -> Result<HeapId, ResourceError> {
        self.tracker.on_allocate(|| data.py_estimate_size())?;
        if data.is_gc_tracked() {
            self.allocations_since_gc = self.allocations_since_gc.wrapping_add(1);
            // Mark potential cycles if this container has heap references.
            // This is essential for types like Dict where setitem doesn't call
            // mark_potential_cycle() - the allocation is the only place to detect refs.
            if data.has_refs() {
                self.may_have_cycles = true;
            }
        }

        let hash_state = HashState::for_data(&data);
        let new_entry = HeapValue {
            refcount: Cell::new(1),
            readers: Cell::new(0),
            data: UnsafeHeapData(UnsafeCell::new(data)),
            hash_state,
        };

        let id = if let Some(id) = self.free_list.pop() {
            // Reuse a freed slot
            *self.entries.get_mut(id.index()) = Some(new_entry);
            id
        } else {
            // No free slots, append new entry
            HeapId(self.entries.push(Some(new_entry)))
        };

        Ok(id)
    }

    /// Returns the singleton empty tuple.
    ///
    /// In Python, `() is ()` is always `True` because empty tuples are interned.
    /// This method provides the same optimization by returning the same `HeapId`
    /// for all empty tuple allocations.
    ///
    /// The returned `Value` has its reference count incremented, so the caller
    /// owns a reference and must call `dec_ref` when done.
    pub fn get_empty_tuple(&mut self) -> Value {
        // Return existing singleton with incremented refcount
        self.inc_ref(EMPTY_TUPLE_ID);
        Value::Ref(EMPTY_TUPLE_ID)
    }

    /// Increments the reference count for an existing heap entry.
    ///
    /// # Panics
    /// Panics if the value ID is invalid or the value has already been freed.
    pub fn inc_ref(&self, id: HeapId) {
        let value = self
            .entries
            .get(id.index())
            .expect("Heap::inc_ref: object already freed");
        value.refcount.update(|r| r + 1);
    }

    /// Decrements the reference count and frees the value (plus children) once it hits zero.
    ///
    /// Uses an iterative work stack instead of recursion to avoid Rust stack overflow
    /// when freeing deeply nested containers (e.g., a list nested 10,000 levels deep).
    /// This is analogous to CPython's "trashcan" mechanism for safe deallocation.
    ///
    /// # Panics
    /// Panics if the value ID is invalid, the value has already been freed, or
    /// the refcount would reach zero while active `HeapRead` readers exist.
    pub fn dec_ref(&mut self, id: HeapId) {
        let mut current_id = id;
        let mut work_stack = Vec::new();
        loop {
            let slot = self.entries.get_mut(current_id.index());
            let entry = slot.as_mut().expect("Heap::dec_ref: object already freed");
            if entry.refcount.get() > 1 {
                entry.refcount.update(|r| r - 1);
            } else {
                assert!(
                    entry.readers.get() == 0,
                    "Heap::dec_ref: cannot free HeapId({}) with {} active reader(s)",
                    current_id.index(),
                    entry.readers.get(),
                );
                if let Some(mut value) = slot.take() {
                    // refcount == 1 and no readers, free the value and add slot to free list
                    self.free_list.push(current_id);

                    // Notify tracker of freed memory
                    self.tracker.on_free(|| value.data.0.get_mut().py_estimate_size());

                    // Collect child IDs and push onto work stack for iterative processing
                    match value.data.0.get_mut() {
                        HeapData::Str(s) => s.py_dec_ref_ids(&mut work_stack),
                        HeapData::Bytes(b) => b.py_dec_ref_ids(&mut work_stack),
                        HeapData::List(l) => l.py_dec_ref_ids(&mut work_stack),
                        HeapData::Tuple(t) => t.py_dec_ref_ids(&mut work_stack),
                        HeapData::NamedTuple(nt) => nt.py_dec_ref_ids(&mut work_stack),
                        HeapData::Dict(d) => d.py_dec_ref_ids(&mut work_stack),
                        HeapData::DictKeysView(view) => view.py_dec_ref_ids(&mut work_stack),
                        HeapData::DictItemsView(view) => view.py_dec_ref_ids(&mut work_stack),
                        HeapData::DictValuesView(view) => view.py_dec_ref_ids(&mut work_stack),
                        HeapData::Set(s) => s.py_dec_ref_ids(&mut work_stack),
                        HeapData::FrozenSet(fs) => fs.py_dec_ref_ids(&mut work_stack),
                        HeapData::Closure(closure) => {
                            // Decrement ref count for captured cells
                            work_stack.extend(closure.cells.iter().copied());
                            // Decrement ref count for default values that are heap references
                            for default in &mut closure.defaults {
                                default.py_dec_ref_ids(&mut work_stack);
                            }
                        }
                        HeapData::FunctionDefaults(fd) => {
                            // Decrement ref count for default values that are heap references
                            for default in &mut fd.defaults {
                                default.py_dec_ref_ids(&mut work_stack);
                            }
                        }
                        HeapData::Cell(cell) => cell.0.py_dec_ref_ids(&mut work_stack),
                        HeapData::Dataclass(dc) => dc.py_dec_ref_ids(&mut work_stack),
                        HeapData::Iter(iter) => iter.py_dec_ref_ids(&mut work_stack),
                        HeapData::Module(m) => m.py_dec_ref_ids(&mut work_stack),
                        HeapData::Coroutine(coro) => {
                            // Decrement ref count for namespace values that are heap references
                            for value in &mut coro.namespace {
                                value.py_dec_ref_ids(&mut work_stack);
                            }
                        }
                        HeapData::GatherFuture(gather) => {
                            // Decrement ref count for coroutine HeapIds
                            for item in &gather.items {
                                if let GatherItem::Coroutine(id) = item {
                                    work_stack.push(*id);
                                }
                            }
                            // Decrement ref count for result values that are heap references
                            for result in gather.results.iter_mut().flatten() {
                                result.py_dec_ref_ids(&mut work_stack);
                            }
                        }
                        // other types have no nested heap references
                        _ => {}
                    }
                }
            }

            let Some(next_id) = work_stack.pop() else {
                break;
            };
            current_id = next_id;
        }
    }

    /// Returns an immutable reference to the heap data stored at the given ID.
    ///
    /// # Panics
    /// Panics if the value ID is invalid, the value has already been freed,
    /// or the data is currently borrowed via `with_entry_mut`/`call_attr`.
    #[must_use]
    pub fn get(&self, id: HeapId) -> &HeapData {
        let data = &self
            .entries
            .get(id.index())
            .expect("Heap::get: object already freed")
            .data;
        // SAFETY: (DH) no mutable references into `HeapData` is possible while the heap is borrowed
        unsafe { &*data.0.get() }
    }

    /// Returns or computes the hash for the heap entry at the given ID.
    ///
    /// Hashes are computed lazily on first use and then cached. Returns
    /// `Ok(Some(hash))` for immutable types, `Ok(None)` for mutable types,
    /// or `Err(ResourceError::Recursion)` if the recursion limit is exceeded.
    ///
    /// # Panics
    /// Panics if the value ID is invalid or the value has already been freed.
    pub fn get_or_compute_hash(&mut self, id: HeapId, interns: &Interns) -> Result<Option<u64>, ResourceError> {
        let entry = self
            .entries
            .get_mut(id.index())
            .as_mut()
            .expect("Heap::get_or_compute_hash: object already freed");

        match entry.hash_state {
            HashState::Unhashable => return Ok(None),
            HashState::Cached(hash) => return Ok(Some(hash)),
            HashState::Unknown => {}
        }

        // Handle Cell specially - uses identity-based hashing (like Python cell objects)
        if let HeapData::Cell(_) = entry.data.0.get_mut() {
            let mut hasher = DefaultHasher::new();
            id.hash(&mut hasher);
            let hash = hasher.finish();
            entry.hash_state = HashState::Cached(hash);
            return Ok(Some(hash));
        }

        // Compute hash via HeapRead — data stays in the heap, no take-and-restore needed.
        let hash = HeapReader::with(self, |reader| {
            let output = reader.read(id);
            compute_hash_from_read(output, id, reader, interns)
        })?;

        // Cache the result
        let entry = self
            .entries
            .get_mut(id.index())
            .as_mut()
            .expect("Heap::get_or_compute_hash: object freed during compute");
        entry.hash_state = match hash {
            Some(value) => HashState::Cached(value),
            None => HashState::Unhashable,
        };
        Ok(hash)
    }

    /// Returns the reference count for the heap entry at the given ID.
    ///
    /// This is primarily used for testing reference counting behavior.
    ///
    /// # Panics
    /// Panics if the value ID is invalid or the value has already been freed.
    #[must_use]
    #[cfg(feature = "ref-count-return")]
    pub fn get_refcount(&self, id: HeapId) -> usize {
        self.entries
            .get(id.index())
            .expect("Heap::get_refcount: object already freed")
            .refcount
            .get()
    }

    /// Returns the number of live (non-freed) values on the heap.
    ///
    /// This is primarily used for testing to verify that all heap entries
    /// are accounted for in reference count tests.
    ///
    /// Excludes the empty tuple singleton since it's an internal optimization
    /// detail that persists even when not explicitly used by user code.
    #[must_use]
    #[cfg(feature = "ref-count-return")]
    pub fn entry_count(&self) -> usize {
        // Skip index 0 which is the empty tuple singleton
        self.entries.iter().skip(1).filter(|o| o.is_some()).count()
    }

    /// Helper for List in-place add: extends the destination vec with items from a heap list.
    ///
    /// This method exists to work around borrow checker limitations when List::py_iadd
    /// needs to read from one heap entry while extending another. By keeping both
    /// the read and the refcount increments within Heap's impl block, we can use the
    /// take/restore pattern to avoid the lifetime propagation issues.
    ///
    /// Returns `true` if successful, `false` if the source ID is not a List.
    pub fn iadd_extend_list(&mut self, source_id: HeapId, dest: &mut Vec<Value>) -> bool {
        if let HeapData::List(list) = self.get(source_id) {
            let items: Vec<Value> = list.as_slice().iter().map(|v| v.clone_with_heap(self)).collect();
            dest.extend(items);
            true
        } else {
            false
        }
    }

    /// Multiplies a heap-allocated value by an `i64`.
    ///
    /// If `id` refers to a `LongInt`, performs integer multiplication with a size
    /// pre-check. Otherwise, treats `id` as a sequence and `int_val` as the repeat
    /// count. This avoids multiple `heap.get()` calls by looking up the data once.
    ///
    /// Returns `Ok(None)` if the heap entry is neither a LongInt nor a sequence type.
    pub fn mult_ref_by_i64(&mut self, id: HeapId, int_val: i64) -> RunResult<Option<Value>> {
        if let HeapData::LongInt(li) = self.get(id) {
            check_mult_size(li.bits(), i64_bits(int_val), &self.tracker)?;
            let result = LongInt::new(li.inner().clone()) * LongInt::from(int_val);
            Ok(Some(result.into_value(self)?))
        } else {
            let count = i64_to_repeat_count(int_val)?;
            self.mult_sequence(id, count)
        }
    }

    /// Multiplies two heap-allocated values.
    ///
    /// Returns Ok(None) for unsupported type combinations.
    pub fn mult_heap_values(&mut self, id1: HeapId, id2: HeapId) -> RunResult<Option<Value>> {
        let (seq_id, count) = match (self.get(id1), self.get(id2)) {
            (HeapData::LongInt(a), HeapData::LongInt(b)) => {
                check_mult_size(a.bits(), b.bits(), &self.tracker)?;
                let result = LongInt::new(a.inner() * b.inner());
                return Ok(Some(result.into_value(self)?));
            }
            (HeapData::LongInt(li), _) => {
                let count = longint_to_repeat_count(li)?;
                (id2, count)
            }
            (_, HeapData::LongInt(li)) => {
                let count = longint_to_repeat_count(li)?;
                (id1, count)
            }
            _ => return Ok(None),
        };

        self.mult_sequence(seq_id, count)
    }

    /// Multiplies (repeats) a sequence by an integer count.
    ///
    /// This method handles sequence repetition for Python's `*` operator when applied
    /// to sequences (str, bytes, list, tuple). It creates a new heap-allocated sequence
    /// with the elements repeated `count` times.
    ///
    /// # Arguments
    /// * `id` - HeapId of the sequence to repeat
    /// * `count` - Number of times to repeat (0 returns empty sequence)
    ///
    /// # Returns
    /// * `Ok(Some(Value))` - The new repeated sequence
    /// * `Ok(None)` - If the heap entry is not a sequence type
    /// * `Err` - If allocation fails due to resource limits
    pub fn mult_sequence(&mut self, id: HeapId, count: usize) -> RunResult<Option<Value>> {
        match self.get(id) {
            HeapData::Str(s) => {
                check_repeat_size(s.len(), count, &self.tracker)?;
                Ok(Some(Value::Ref(
                    self.allocate(HeapData::Str(s.as_str().repeat(count).into()))?,
                )))
            }
            HeapData::Bytes(b) => {
                check_repeat_size(b.len(), count, &self.tracker)?;
                Ok(Some(Value::Ref(
                    self.allocate(HeapData::Bytes(b.as_slice().repeat(count).into()))?,
                )))
            }
            HeapData::List(list) => {
                check_repeat_size(list.len().saturating_mul(size_of::<Value>()), count, &self.tracker)?;
                let mut result = Vec::with_capacity(list.as_slice().len() * count);
                for _ in 0..count {
                    result.extend(list.as_slice().iter().map(|v| v.clone_with_heap(self)));
                    self.check_time()?;
                }
                Ok(Some(Value::Ref(self.allocate(HeapData::List(List::new(result)))?)))
            }
            HeapData::Tuple(tuple) => {
                if count == 0 {
                    return Ok(Some(self.get_empty_tuple()));
                }
                check_repeat_size(
                    tuple.as_slice().len().saturating_mul(size_of::<Value>()),
                    count,
                    &self.tracker,
                )?;
                let mut result = SmallVec::with_capacity(tuple.as_slice().len() * count);
                for _ in 0..count {
                    result.extend(tuple.as_slice().iter().map(|v| v.clone_with_heap(self)));
                    self.check_time()?;
                }
                Ok(Some(allocate_tuple(result, self)?))
            }
            _ => Ok(None),
        }
    }

    /// Returns whether garbage collection should run.
    ///
    /// True if reference cycles count exist in the heap
    /// and the number of allocations since the last GC exceeds the interval.
    #[inline]
    pub fn should_gc(&self) -> bool {
        self.may_have_cycles && self.allocations_since_gc >= GC_INTERVAL
    }

    /// Runs mark-sweep garbage collection to free unreachable cycles.
    ///
    /// This method takes a closure that provides an iterator of root HeapIds
    /// (typically from the VM's globals and stack). It marks all reachable objects starting
    /// from roots, then sweeps (frees) any unreachable objects.
    ///
    /// This is necessary because reference counting alone cannot free cycles
    /// where objects reference each other but are unreachable from the program.
    ///
    /// # Caller Responsibility
    /// The caller should check `should_gc()` before calling this method.
    /// If no cycles are possible, the caller can skip GC entirely.
    ///
    /// # Arguments
    /// * `root` - HeapIds that are roots
    pub fn collect_garbage(&mut self, root: Vec<HeapId>) {
        // Mark phase: collect all reachable IDs using BFS
        // Use Vec<bool> instead of HashSet for O(1) operations without hashing overhead
        let mut reachable: Vec<bool> = vec![false; self.entries.len()];
        let mut work_list: Vec<HeapId> = root;

        while let Some(id) = work_list.pop() {
            let idx = id.index();
            // Skip if out of bounds or already visited
            if idx >= reachable.len() || reachable[idx] {
                continue;
            }
            reachable[idx] = true;

            // Add children to work list
            if let Some(Some(entry)) = self.entries.try_get_mut(idx) {
                collect_child_ids(entry.data.0.get_mut(), &mut work_list);
            }
        }

        // Sweep phase: free unreachable values
        for (id, value) in self.entries.iter_mut().enumerate() {
            if reachable[id] {
                continue;
            }

            // This entry is unreachable - free it
            if let Some(mut value) = value.take() {
                // Notify tracker of freed memory
                self.tracker.on_free(|| value.data.0.get_mut().py_estimate_size());

                self.free_list.push(HeapId(id));

                // Mark Values as Dereferenced when ref-count-panic is enabled
                #[cfg(feature = "ref-count-panic")]
                value.data.0.get_mut().py_dec_ref_ids(&mut Vec::new());
            }
        }

        // Reset cycle flag after GC - cycles have been collected
        self.may_have_cycles = false;
        self.allocations_since_gc = 0;
    }
}

/// Computes the number of significant bits in an `i64`.
///
/// Returns 0 for zero, otherwise returns the position of the highest set bit
/// plus one. Uses unsigned absolute value to handle negative numbers correctly.
fn i64_bits(value: i64) -> u64 {
    if value == 0 {
        0
    } else {
        u64::from(64 - value.unsigned_abs().leading_zeros())
    }
}

/// Converts an `i64` repeat count to `usize` for sequence repetition.
///
/// Returns 0 for negative values (Python treats negative repeat counts as 0).
/// Returns `OverflowError` if the value exceeds `usize::MAX`.
fn i64_to_repeat_count(n: i64) -> RunResult<usize> {
    if n <= 0 {
        Ok(0)
    } else {
        usize::try_from(n).map_err(|_| ExcType::overflow_repeat_count().into())
    }
}

/// Converts a `LongInt` repeat count to `usize` for sequence repetition.
///
/// Returns 0 for negative values (Python treats negative repeat counts as 0).
/// Returns `OverflowError` if the value exceeds `usize::MAX`.
fn longint_to_repeat_count(li: &LongInt) -> RunResult<usize> {
    if li.is_negative() {
        Ok(0)
    } else if let Some(count) = li.to_usize() {
        Ok(count)
    } else {
        Err(ExcType::overflow_repeat_count().into())
    }
}

/// Computes the hash for a heap value via the `HeapRead` pattern.
///
/// Data stays in the heap throughout — no take-and-restore needed. For recursive types
/// (Tuple, NamedTuple, FrozenSet, Dataclass), uses the short-lived borrow pattern:
/// read element via shared borrow, release borrow, then recurse into `get_or_compute_hash`
/// for Ref children.
///
/// Returns `Ok(Some(hash))` for hashable types, `Ok(None)` for unhashable types,
/// or `Err(ResourceError::Recursion)` if the recursion limit is exceeded.
fn compute_hash_from_read<'a, T: ResourceTracker>(
    output: HeapReadOutput<'a>,
    id: HeapId,
    reader: &mut HeapReader<'a, T>,
    interns: &Interns,
) -> Result<Option<u64>, ResourceError> {
    /// Helper to get the `HeapData` discriminant for mixing into hashes.
    /// Uses a short-lived borrow on the reader.
    fn heap_disc<T: ResourceTracker>(reader: &HeapReader<'_, T>, id: HeapId) -> std::mem::Discriminant<HeapData> {
        discriminant(reader.get(id))
    }

    match output {
        // Str/Bytes: hash just the content (consistent with InternString/InternBytes)
        HeapReadOutput::Str(s) => {
            let mut hasher = DefaultHasher::new();
            s.get(&*reader).as_str().hash(&mut hasher);
            Ok(Some(hasher.finish()))
        }
        HeapReadOutput::Bytes(b) => {
            let mut hasher = DefaultHasher::new();
            b.get(&*reader).as_slice().hash(&mut hasher);
            Ok(Some(hasher.finish()))
        }
        // Tuple: hashable only if all elements are hashable
        HeapReadOutput::Tuple(tuple) => {
            let token = reader.incr_recursion_depth()?;
            crate::defer_drop!(token, reader);
            let len = tuple.get(&*reader).as_slice().len();
            let mut hasher = DefaultHasher::new();
            heap_disc(&*reader, id).hash(&mut hasher);
            for i in 0..len {
                let h = hash_element_at(|r| &tuple.get(r).as_slice()[i], reader, interns)?;
                match h {
                    Some(h) => h.hash(&mut hasher),
                    None => return Ok(None),
                }
            }
            Ok(Some(hasher.finish()))
        }
        // NamedTuple: hash by elements only (not type_name) to match equality semantics
        HeapReadOutput::NamedTuple(nt) => {
            let token = reader.incr_recursion_depth()?;
            crate::defer_drop!(token, reader);
            let len = nt.get(&*reader).as_vec().len();
            let mut hasher = DefaultHasher::new();
            heap_disc(&*reader, id).hash(&mut hasher);
            for i in 0..len {
                let h = hash_element_at(|r| &nt.get(r).as_vec()[i], reader, interns)?;
                match h {
                    Some(h) => h.hash(&mut hasher),
                    None => return Ok(None),
                }
            }
            Ok(Some(hasher.finish()))
        }
        // FrozenSet: XOR of all element hashes (order-independent).
        HeapReadOutput::FrozenSet(fs) => {
            let token = reader.incr_recursion_depth()?;
            crate::defer_drop!(token, reader);
            let len = fs.get(&*reader).storage().entry_count();
            let mut hash: u64 = 0;
            for i in 0..len {
                let h = hash_element_at(|r| fs.get(r).storage().entry_value(i), reader, interns)?;
                match h {
                    Some(h) => hash ^= h,
                    None => return Ok(None),
                }
            }
            Ok(Some(hash))
        }
        // Dataclass: hash frozen instances by class name + declared field values
        HeapReadOutput::Dataclass(dc) => {
            let is_frozen = dc.get(&*reader).is_frozen();
            if !is_frozen {
                return Ok(None);
            }
            let token = reader.incr_recursion_depth()?;
            crate::defer_drop!(token, reader);
            let mut hasher = DefaultHasher::new();
            // Clone field names so we can iterate without holding the borrow
            let field_names: Vec<String> = dc.get(&*reader).field_names().to_vec();
            // Hash the class name (via accessor, hashing the string content)
            dc.get(&*reader).name(interns).hash(&mut hasher);
            // Hash each declared field (name, value) pair in order
            for field_name in &field_names {
                field_name.hash(&mut hasher);
                // get_by_str only needs &Heap (immutable), compatible with HeapRead borrow
                let ref_id = {
                    match dc.get(&*reader).attrs().get_by_str(field_name, &*reader, interns) {
                        Some(Value::Ref(id)) => Some(Some(*id)),
                        Some(_) => Some(None),
                        None => None,
                    }
                };
                if let Some(value_info) = ref_id {
                    let h = if let Some(id) = value_info {
                        reader.get_or_compute_hash(id, interns)?
                    } else {
                        let v = dc
                            .get(&*reader)
                            .attrs()
                            .get_by_str(field_name, &*reader, interns)
                            .unwrap()
                            .clone_immediate();
                        v.py_hash(&mut **reader, interns)?
                    };
                    match h {
                        Some(h) => h.hash(&mut hasher),
                        None => return Ok(None),
                    }
                }
            }
            Ok(Some(hasher.finish()))
        }
        // Closure/FunctionDefaults: hash by function ID
        HeapReadOutput::Closure(closure) => {
            let func_id = closure.get(&*reader).func_id;
            let mut hasher = DefaultHasher::new();
            heap_disc(&*reader, id).hash(&mut hasher);
            func_id.hash(&mut hasher);
            Ok(Some(hasher.finish()))
        }
        HeapReadOutput::FunctionDefaults(fd) => {
            let func_id = fd.get(&*reader).func_id;
            let mut hasher = DefaultHasher::new();
            heap_disc(&*reader, id).hash(&mut hasher);
            func_id.hash(&mut hasher);
            Ok(Some(hasher.finish()))
        }
        // Range: hash start, stop, step
        HeapReadOutput::Range(range) => {
            let r = range.get(&*reader);
            let mut hasher = DefaultHasher::new();
            heap_disc(&*reader, id).hash(&mut hasher);
            r.start.hash(&mut hasher);
            r.stop.hash(&mut hasher);
            r.step.hash(&mut hasher);
            Ok(Some(hasher.finish()))
        }
        // Slice: hash start, stop, step
        HeapReadOutput::Slice(slice) => {
            let s = slice.get(&*reader);
            let mut hasher = DefaultHasher::new();
            heap_disc(&*reader, id).hash(&mut hasher);
            s.start.hash(&mut hasher);
            s.stop.hash(&mut hasher);
            s.step.hash(&mut hasher);
            Ok(Some(hasher.finish()))
        }
        // Path: hash the path string
        HeapReadOutput::Path(path) => {
            let mut hasher = DefaultHasher::new();
            heap_disc(&*reader, id).hash(&mut hasher);
            path.get(&*reader).as_str().hash(&mut hasher);
            Ok(Some(hasher.finish()))
        }
        // LongInt: uses its own hash method
        HeapReadOutput::LongInt(li) => Ok(Some(li.get(&*reader).hash())),
        // ExtFunction: hash by name
        HeapReadOutput::ExtFunction(name) => {
            let mut hasher = DefaultHasher::new();
            heap_disc(&*reader, id).hash(&mut hasher);
            name.get(&*reader).hash(&mut hasher);
            Ok(Some(hasher.finish()))
        }
        // All other types are unhashable
        _ => Ok(None),
    }
}

/// Hashes a single element from a container using the short-lived borrow pattern.
///
/// The `read_element` closure reads `&Value` from the container via a shared borrow on the
/// reader. If the element is `Ref(id)`, the borrow is released and `get_or_compute_hash`
/// is called recursively. For non-Ref values, the element is cloned via `clone_immediate()`
/// and hashed directly (non-Ref values never need heap access for hashing).
fn hash_element_at<'a, T: ResourceTracker>(
    read_element: impl for<'r> Fn(&'r HeapReader<'a, T>) -> &'r Value,
    reader: &mut HeapReader<'a, T>,
    interns: &Interns,
) -> Result<Option<u64>, ResourceError> {
    let ref_id = match read_element(&*reader) {
        Value::Ref(id) => Some(*id),
        _ => None,
    };
    if let Some(id) = ref_id {
        reader.get_or_compute_hash(id, interns)
    } else {
        let value = read_element(&*reader).clone_immediate();
        value.py_hash(&mut **reader, interns)
    }
}

/// Collects child HeapIds from a HeapData value for GC traversal.
fn collect_child_ids(data: &HeapData, work_list: &mut Vec<HeapId>) {
    match data {
        HeapData::List(list) => {
            // Skip iteration if no refs - major GC optimization for lists of primitives
            if !list.contains_refs() {
                return;
            }
            for value in list.as_slice() {
                if let Value::Ref(id) = value {
                    work_list.push(*id);
                }
            }
        }
        HeapData::Tuple(tuple) => {
            // Skip iteration if no refs - GC optimization for tuples of primitives
            if !tuple.contains_refs() {
                return;
            }
            for value in tuple.as_slice() {
                if let Value::Ref(id) = value {
                    work_list.push(*id);
                }
            }
        }
        HeapData::NamedTuple(nt) => {
            // Skip iteration if no refs - GC optimization for namedtuples of primitives
            if !nt.contains_refs() {
                return;
            }
            for value in nt.as_vec() {
                if let Value::Ref(id) = value {
                    work_list.push(*id);
                }
            }
        }
        HeapData::Dict(dict) => {
            // Skip iteration if no refs - major GC optimization for dicts of primitives
            if !dict.has_refs() {
                return;
            }
            for (k, v) in dict {
                if let Value::Ref(id) = k {
                    work_list.push(*id);
                }
                if let Value::Ref(id) = v {
                    work_list.push(*id);
                }
            }
        }
        HeapData::DictKeysView(view) => {
            work_list.push(view.dict_id());
        }
        HeapData::DictItemsView(view) => {
            work_list.push(view.dict_id());
        }
        HeapData::DictValuesView(view) => {
            work_list.push(view.dict_id());
        }
        HeapData::Set(set) => {
            for value in set.storage().iter() {
                if let Value::Ref(id) = value {
                    work_list.push(*id);
                }
            }
        }
        HeapData::FrozenSet(frozenset) => {
            for value in frozenset.storage().iter() {
                if let Value::Ref(id) = value {
                    work_list.push(*id);
                }
            }
        }
        HeapData::Closure(closure) => {
            // Add captured cells to work list
            for cell_id in &closure.cells {
                work_list.push(*cell_id);
            }
            // Add default values that are heap references
            for default in &closure.defaults {
                if let Value::Ref(id) = default {
                    work_list.push(*id);
                }
            }
        }
        HeapData::FunctionDefaults(fd) => {
            // Add default values that are heap references
            for default in &fd.defaults {
                if let Value::Ref(id) = default {
                    work_list.push(*id);
                }
            }
        }
        HeapData::Cell(cell) => {
            // Cell can contain a reference to another heap value
            if let Value::Ref(id) = &cell.0 {
                work_list.push(*id);
            }
        }
        HeapData::Dataclass(dc) => {
            // Dataclass attrs are stored in a Dict - iterate through entries
            for (k, v) in dc.attrs() {
                if let Value::Ref(id) = k {
                    work_list.push(*id);
                }
                if let Value::Ref(id) = v {
                    work_list.push(*id);
                }
            }
        }
        HeapData::Iter(iter) => {
            // Iterator holds a reference to the iterable being iterated
            if let Value::Ref(id) = iter.value() {
                work_list.push(*id);
            }
        }
        HeapData::Module(m) => {
            // Module attrs can contain references to heap values
            if !m.has_refs() {
                return;
            }
            for (k, v) in m.attrs() {
                if let Value::Ref(id) = k {
                    work_list.push(*id);
                }
                if let Value::Ref(id) = v {
                    work_list.push(*id);
                }
            }
        }
        HeapData::Coroutine(coro) => {
            // Add namespace values that are heap references
            for value in &coro.namespace {
                if let Value::Ref(id) = value {
                    work_list.push(*id);
                }
            }
        }
        HeapData::GatherFuture(gather) => {
            // Add coroutine HeapIds to work list
            for item in &gather.items {
                if let GatherItem::Coroutine(coro_id) = item {
                    work_list.push(*coro_id);
                }
            }
            // Add result values that are heap references
            for result in gather.results.iter().flatten() {
                if let Value::Ref(id) = result {
                    work_list.push(*id);
                }
            }
        }
        // Leaf types with no heap references
        _ => {}
    }
}

/// Drop implementation for Heap that marks all contained Objects as Dereferenced
/// before dropping to prevent panics when the `ref-count-panic` feature is enabled.
#[cfg(feature = "ref-count-panic")]
impl<T: ResourceTracker> Drop for Heap<T> {
    fn drop(&mut self) {
        // Mark all contained Objects as Dereferenced before dropping.
        // We use py_dec_ref_ids for this since it handles the marking
        // (we ignore the collected IDs since we're dropped everything anyway).
        let mut dummy_stack = Vec::new();
        for value in self.entries.iter_mut().filter_map(|o| o.as_mut()) {
            value.data.0.get_mut().py_dec_ref_ids(&mut dummy_stack);
        }
    }
}

/// Compile-fail soundness tests for [`HeapReader`].
///
/// Gated behind `--cfg heap_reader_compile_fail_tests` so they are only compiled
/// when the integration test harness runs `cargo check` with the appropriate flags.
#[cfg(heap_reader_compile_fail_tests)]
#[path = "../tests/heap_reader_compile_fail_cases/cases.rs"]
mod heap_reader_compile_fail_cases;
