# Based on python/typeshed's `stdlib/binascii.pyi`, cut down to what Monty
# exposes at runtime. The remaining conversions (`a2b_uu`, `b2a_uu`, `a2b_qp`,
# `b2a_qp`) are absent so type checking rejects them up front instead of
# letting them fail with `AttributeError`. Extend in lockstep with
# `crates/monty/src/modules/binascii.rs`.

class Error(ValueError): ...

def hexlify(data: bytes, sep: str | bytes = ..., bytes_per_sep: int = 1) -> bytes: ...
def b2a_hex(data: bytes, sep: str | bytes = ..., bytes_per_sep: int = 1) -> bytes: ...
def unhexlify(hexstr: str | bytes, /) -> bytes: ...
def a2b_hex(hexstr: str | bytes, /) -> bytes: ...
def b2a_base64(data: bytes, /, *, newline: bool = True) -> bytes: ...
def a2b_base64(data: str | bytes, /, *, strict_mode: bool = False) -> bytes: ...
def crc32(data: bytes, crc: int = 0, /) -> int: ...
