# Based on python/typeshed's `stdlib/binascii.pyi`, cut down to what Monty
# exposes at runtime. Extend in lockstep with
# `crates/monty/src/modules/binascii.rs`.
#
# Parameters typed `ReadableBuffer` upstream are `bytes` here: Monty has no
# `bytearray` or `memoryview`.

class Error(ValueError): ...
class Incomplete(Exception): ...

def hexlify(data: bytes, sep: str | bytes = ..., bytes_per_sep: int = 1) -> bytes: ...
def b2a_hex(data: bytes, sep: str | bytes = ..., bytes_per_sep: int = 1) -> bytes: ...
def unhexlify(hexstr: str | bytes, /) -> bytes: ...
def a2b_hex(hexstr: str | bytes, /) -> bytes: ...
def b2a_base64(data: bytes, /, *, newline: bool = True) -> bytes: ...
def a2b_base64(data: str | bytes, /, *, strict_mode: bool = False) -> bytes: ...
def b2a_uu(data: bytes, /, *, backtick: bool = False) -> bytes: ...
def a2b_uu(data: str | bytes, /) -> bytes: ...
def b2a_qp(data: bytes, quotetabs: bool = False, istext: bool = True, header: bool = False) -> bytes: ...
def a2b_qp(data: str | bytes, header: bool = False) -> bytes: ...
def crc32(data: bytes, crc: int = 0, /) -> int: ...
def crc_hqx(data: bytes, crc: int, /) -> int: ...
