# Upstream typeshed re-exports `decimal` from `_decimal.pyi`; Monty implements
# only a subset (a fixed default context — no `Context` objects or `getcontext`
# — and a reduced method set), so this stub describes *only* the surface Monty
# supports. Methods absent here (compare_total, fma, scaleb, shift, rotate,
# logb, next_*, …) are intentionally omitted so they type-error instead of
# silently passing.

from collections.abc import Sequence
from typing import ClassVar, Final, Literal, NamedTuple, overload

ROUND_DOWN: Final[str]
ROUND_HALF_UP: Final[str]
ROUND_HALF_EVEN: Final[str]
ROUND_CEILING: Final[str]
ROUND_FLOOR: Final[str]
ROUND_UP: Final[str]
ROUND_HALF_DOWN: Final[str]
ROUND_05UP: Final[str]

class DecimalTuple(NamedTuple):
    sign: int
    digits: tuple[int, ...]
    exponent: int | Literal['n', 'N', 'F']

class DecimalException(ArithmeticError): ...
class Clamped(DecimalException): ...
class InvalidOperation(DecimalException): ...
class ConversionSyntax(InvalidOperation): ...
class DivisionByZero(DecimalException, ZeroDivisionError): ...
class DivisionImpossible(InvalidOperation): ...
class DivisionUndefined(InvalidOperation, ZeroDivisionError): ...
class Inexact(DecimalException): ...
class InvalidContext(InvalidOperation): ...
class Rounded(DecimalException): ...
class Subnormal(DecimalException): ...
class Overflow(Inexact, Rounded): ...
class Underflow(Inexact, Rounded, Subnormal): ...
class FloatOperation(DecimalException, TypeError): ...

# Accepted by `Decimal(...)`; the tuple form is `(sign, digits, exponent)`.
_DecimalNew = Decimal | float | str | tuple[int, Sequence[int], int]
# Accepted as the *other* operand in arithmetic/comparison (Decimal ⊕ int).
_ComparableNum = Decimal | int

class Decimal:
    # `from_float(x)` is not implemented; use `Decimal(x)` directly (it accepts
    # `float` and produces the identical exact value). See `limitations/decimal.md`.
    def __new__(cls, value: _DecimalNew = ...) -> Decimal: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __lt__(self, value: _ComparableNum, /) -> bool: ...
    def __le__(self, value: _ComparableNum, /) -> bool: ...
    def __gt__(self, value: _ComparableNum, /) -> bool: ...
    def __ge__(self, value: _ComparableNum, /) -> bool: ...
    def __add__(self, value: _ComparableNum, /) -> Decimal: ...
    def __radd__(self, value: int, /) -> Decimal: ...
    def __sub__(self, value: _ComparableNum, /) -> Decimal: ...
    def __rsub__(self, value: int, /) -> Decimal: ...
    def __mul__(self, value: _ComparableNum, /) -> Decimal: ...
    def __rmul__(self, value: int, /) -> Decimal: ...
    def __truediv__(self, value: _ComparableNum, /) -> Decimal: ...
    def __rtruediv__(self, value: int, /) -> Decimal: ...
    def __floordiv__(self, value: _ComparableNum, /) -> Decimal: ...
    def __rfloordiv__(self, value: int, /) -> Decimal: ...
    def __mod__(self, value: _ComparableNum, /) -> Decimal: ...
    def __rmod__(self, value: int, /) -> Decimal: ...
    def __divmod__(self, value: _ComparableNum, /) -> tuple[Decimal, Decimal]: ...
    def __rdivmod__(self, value: int, /) -> tuple[Decimal, Decimal]: ...
    def __pow__(self, value: _ComparableNum, /) -> Decimal: ...
    def __rpow__(self, value: int, /) -> Decimal: ...
    def __neg__(self) -> Decimal: ...
    def __pos__(self) -> Decimal: ...
    def __abs__(self) -> Decimal: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    @overload
    def __round__(self) -> int: ...
    @overload
    def __round__(self, ndigits: int, /) -> Decimal: ...
    def __format__(self, specifier: str, /) -> str: ...
    # Monty has no `Context` objects, so the CPython `context=` argument is not
    # accepted anywhere (passing one raises `TypeError`); the per-call
    # `rounding=` argument is supported where shown below — everything else runs
    # under the fixed default context (see `limitations/decimal.md`).
    def quantize(self, exp: _ComparableNum, rounding: str | None = None) -> Decimal: ...
    def normalize(self) -> Decimal: ...
    def to_integral_value(self, rounding: str | None = None) -> Decimal: ...
    def sqrt(self) -> Decimal: ...
    def ln(self) -> Decimal: ...
    def log10(self) -> Decimal: ...
    def exp(self) -> Decimal: ...
    def as_tuple(self) -> DecimalTuple: ...
    def is_nan(self) -> bool: ...
    def is_qnan(self) -> bool: ...
    def is_snan(self) -> bool: ...
    def is_infinite(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def is_zero(self) -> bool: ...
    def is_signed(self) -> bool: ...
    def copy_abs(self) -> Decimal: ...
    def copy_negate(self) -> Decimal: ...
    def copy_sign(self, other: _ComparableNum, /) -> Decimal: ...
    def adjusted(self) -> int: ...

__all__: ClassVar[list[str]]
