# Based on python/typeshed's `stdlib/itertools.pyi`, stripped down to the
# callables Monty actually implements at runtime.
#
# Everything else (`tee`, `count.__length_hint__`, …) is deliberately absent so
# type checking rejects it up front, rather than passing and then raising
# `AttributeError` at runtime. Extend this in lockstep with
# `crates/monty/src/modules/itertools.rs`.
#
# Narrower than upstream on purpose: `_N` is constrained to `int`/`float`
# because Monty's `count()` rejects anything else, where CPython accepts any
# number protocol.

from collections.abc import Callable, Iterable, Iterator
from typing import Any, Generic, TypeAlias, TypeVar, overload

from typing_extensions import Self

_T = TypeVar('_T')
# `chain.from_iterable` binds its own variable: the class's `_T` is fixed by
# the receiver, which for a classmethod carries no element type.
_S = TypeVar('_S')
# The key `groupby` groups by, which need not be the item type.
_K = TypeVar('_K')
_N = TypeVar('_N', int, float)

_Step: TypeAlias = int | float

class count(Generic[_N]):
    @overload
    def __new__(cls) -> count[int]: ...
    @overload
    def __new__(cls, start: _N, step: _Step = 1) -> count[_N]: ...
    @overload
    def __new__(cls, *, step: _N) -> count[_N]: ...
    def __next__(self) -> _N: ...
    def __iter__(self) -> Self: ...

class repeat(Generic[_T]):
    @overload
    def __new__(cls, object: _T) -> Self: ...
    @overload
    def __new__(cls, object: _T, times: int) -> Self: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Self: ...

class pairwise(Generic[_T]):
    def __new__(cls, iterable: Iterable[_T], /) -> Self: ...
    def __next__(self) -> tuple[_T, _T]: ...
    def __iter__(self) -> Self: ...

class compress(Generic[_T]):
    def __new__(cls, data: Iterable[_T], selectors: Iterable[object]) -> Self: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Self: ...

class islice(Generic[_T]):
    @overload
    def __new__(cls, iterable: Iterable[_T], stop: int | None, /) -> Self: ...
    @overload
    def __new__(cls, iterable: Iterable[_T], start: int | None, stop: int | None, step: int | None = 1, /) -> Self: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Self: ...

class chain(Generic[_T]):
    def __new__(cls, *iterables: Iterable[_T]) -> Self: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Self: ...
    # Declared without `@classmethod` (which upstream typeshed uses): Monty
    # exposes it as a plain function on the class, and the decorated form is
    # inferred as `Unknown` by the checker.
    def from_iterable(iterable: Iterable[Iterable[_S]], /) -> chain[_S]: ...

class cycle(Generic[_T]):
    def __new__(cls, iterable: Iterable[_T], /) -> Self: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Self: ...

class takewhile(Generic[_T]):
    def __new__(cls, predicate: Callable[[_T], object], iterable: Iterable[_T], /) -> Self: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Self: ...

class dropwhile(Generic[_T]):
    def __new__(cls, predicate: Callable[[_T], object], iterable: Iterable[_T], /) -> Self: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Self: ...

class filterfalse(Generic[_T]):
    def __new__(cls, predicate: Callable[[_T], object] | None, iterable: Iterable[_T], /) -> Self: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Self: ...

# Upstream typeshed overloads `starmap` per arity; Monty spreads each item
# dynamically, so one `Callable[..., _T]` covers every shape it accepts.
class starmap(Generic[_T]):
    def __new__(cls, function: Callable[..., _T], iterable: Iterable[Iterable[Any]], /) -> Self: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Self: ...

class accumulate(Generic[_T]):
    @overload
    def __new__(cls, iterable: Iterable[_T], func: None = None, *, initial: _T | None = ...) -> Self: ...
    @overload
    def __new__(cls, iterable: Iterable[_T], func: Callable[[_T, _T], _T], *, initial: _T | None = ...) -> Self: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Self: ...

class batched(Generic[_T]):
    def __new__(cls, iterable: Iterable[_T], n: int, *, strict: bool = False) -> Self: ...
    def __next__(self) -> tuple[_T, ...]: ...
    def __iter__(self) -> Self: ...

# Upstream typeshed overloads `zip_longest` per arity to type each slot;
# Monty takes any number of iterables, so one homogeneous signature covers
# every shape it accepts.
class zip_longest(Generic[_T]):
    def __new__(cls, *iterables: Iterable[_T], fillvalue: Any = None) -> Self: ...
    def __next__(self) -> tuple[Any, ...]: ...
    def __iter__(self) -> Self: ...

class combinations(Generic[_T]):
    def __new__(cls, iterable: Iterable[_T], r: int) -> Self: ...
    def __next__(self) -> tuple[_T, ...]: ...
    def __iter__(self) -> Self: ...

class combinations_with_replacement(Generic[_T]):
    def __new__(cls, iterable: Iterable[_T], r: int) -> Self: ...
    def __next__(self) -> tuple[_T, ...]: ...
    def __iter__(self) -> Self: ...

class permutations(Generic[_T]):
    def __new__(cls, iterable: Iterable[_T], r: int | None = ...) -> Self: ...
    def __next__(self) -> tuple[_T, ...]: ...
    def __iter__(self) -> Self: ...

# Upstream typeshed overloads `product` per arity to type each slot; Monty
# takes any number of iterables, so one homogeneous signature covers every
# shape it accepts — as for `zip_longest` above.
class product(Generic[_T]):
    def __new__(cls, *iterables: Iterable[Any], repeat: int = 1) -> Self: ...
    def __next__(self) -> tuple[Any, ...]: ...
    def __iter__(self) -> Self: ...

# Generic over the key as well as the item, so a supplied `key` types what the
# pairs carry: without `_K` every key would come back as `Any`.
class groupby(Generic[_K, _T]):
    @overload
    def __new__(cls, iterable: Iterable[_T], key: None = None) -> groupby[_T, _T]: ...
    @overload
    def __new__(cls, iterable: Iterable[_T], key: Callable[[_T], _K]) -> groupby[_K, _T]: ...
    # The group is typed as a plain iterator rather than as the
    # `itertools._grouper` upstream typeshed declares: CPython exposes that
    # name on the module and Monty does not, so declaring it here would let
    # `from itertools import _grouper` type-check and then fail at runtime.
    def __next__(self) -> tuple[_K, Iterator[_T]]: ...
    def __iter__(self) -> Self: ...
