//! Writes one version's golden dump fixtures, from inside a checkout of the
//! build that wrote them.
//!
//! Not compiled in this tree: `scripts/generate_golden_dumps.py` copies it into a
//! `git archive` export of an old commit as `crates/monty/tests/generate_golden_dumps.rs` and
//! runs it as a test there. It must stay within the API those commits share:
//! `MontyRepl::new`, `feed_run`, `dump`.
//!
//! Output is the fixture bytes plus a manifest of what this build saw, the ground
//! truth a later build's restore is compared against.

use std::{collections::BTreeMap, env, fs, path::PathBuf};

use monty::{DUMP_VERSION, MontyRepl, SessionRef, dump};
use monty_types::{CompileOptions, PrintWriter, ResourceTracker};
use serde_json::{Map, Value, json};

/// Dumps every corpus case and writes `<out>/<case>.dump` plus `<out>/manifest.json`.
///
/// Configured by environment because it runs as a test: `MONTY_CORPUS` (case
/// sources are read from `cases/<name>.py` beside it), `MONTY_FIXTURE_OUT`, and
/// `MONTY_FIXTURE_COMMIT`/`MONTY_FIXTURE_SUBJECT` for provenance.
#[test]
fn generate_golden_dumps() {
    let corpus_path = PathBuf::from(env_var("MONTY_CORPUS"));
    let corpus: Value = serde_json::from_str(&fs::read_to_string(&corpus_path).expect("corpus is readable"))
        .expect("corpus parses");
    let cases_dir = corpus_path.parent().expect("the corpus has a directory").join("cases");
    let out = PathBuf::from(env_var("MONTY_FIXTURE_OUT"));
    fs::create_dir_all(&out).expect("fixture directory is creatable");

    let mut cases = Map::new();
    for case in corpus["cases"].as_array().expect("cases is an array") {
        let name = case["name"].as_str().expect("case has a name");
        let source_path = cases_dir.join(format!("{name}.py"));
        let source = fs::read_to_string(&source_path)
            .unwrap_or_else(|_| panic!("missing case source {}", source_path.display()));

        let mut repl = MontyRepl::new("golden.py", ResourceTracker::default(), CompileOptions::default());
        repl.feed_run(&source, vec![], PrintWriter::Stdout)
            .unwrap_or_else(|err| panic!("case {name} does not run at version {DUMP_VERSION}: {err:?}"));

        // The state a later build's restore has to reproduce.
        let mut expected = BTreeMap::new();
        for global in case["globals"].as_array().expect("globals is an array") {
            let global = global.as_str().expect("global is a name");
            expected.insert(global.to_owned(), repr_of(&mut repl, global, name));
        }
        let feed = case["feed"].as_str().expect("case has a feed");
        let feed_result = repr_of(&mut repl, &format!("({feed})"), name);

        // Dumped after the feed, so the fixture holds a session that has run more than once.
        let bytes = dump("golden.py", None, SessionRef::Idle(&repl)).expect("dump succeeds");
        fs::write(out.join(format!("{name}.dump")), &bytes).expect("fixture is writable");

        cases.insert(
            name.to_owned(),
            json!({
                "file": format!("{name}.dump"),
                "bytes": bytes.len(),
                "expected": expected,
                "feed_result": feed_result,
            }),
        );
    }

    let manifest = json!({
        "doc": "Generated by `make generate-golden-dumps`. Do not edit by hand.",
        "dump_version": DUMP_VERSION,
        "commit": env_var("MONTY_FIXTURE_COMMIT"),
        "subject": env_var("MONTY_FIXTURE_SUBJECT"),
        "cases": cases,
    });
    let mut rendered = serde_json::to_string_pretty(&manifest).expect("manifest serializes");
    rendered.push('\n');
    fs::write(out.join("manifest.json"), rendered).expect("manifest is writable");
}

/// Evaluates `repr(expr)` in the session.
///
/// The repr is computed by the sandbox and read back through `Display`, which
/// writes a `str` as its raw text in every `MontyObject` shape this file has to
/// compile against (an enum at version 10, a graph struct from 11 on).
fn repr_of(repl: &mut MontyRepl, expr: &str, case: &str) -> String {
    repl.feed_run(&format!("repr({expr})"), vec![], PrintWriter::Stdout)
        .unwrap_or_else(|err| panic!("case {case} cannot repr {expr}: {err:?}"))
        .to_string()
}

/// Reads a required environment variable set by the Python driver.
fn env_var(name: &str) -> String {
    env::var(name).unwrap_or_else(|_| panic!("{name} must be set; run `make generate-golden-dumps`"))
}
