//! Implementation of Python's `dataclasses` module.
//!
//! Native, in-sandbox `@dataclass`: the decorator writes a `__dataclass_fields__`
//! mapping of [`DataclassField`]s into the class namespace and the dunders are
//! synthesized off it — no `exec`, no generated bytecode. This module owns the
//! whole feature; the generic machinery calls in through narrow hooks in
//! `bytecode::vm::call` (construction) and `types::instance` (value dunders).
//!
//! See `limitations/dataclasses.md` for divergences from CPython.

mod field;
mod options;

use std::{
    collections::hash_map::DefaultHasher,
    fmt::Write,
    hash::{Hash, Hasher},
    mem,
};

use self::field::{adoptable_field, field_at, field_at_id};
pub(crate) use self::{field::DataclassField, options::DataclassParams};
use crate::{
    args::{ArgValues, FromArgs, KwargsValues},
    builtins::Builtins,
    bytecode::{CallResult, VM},
    defer_drop, defer_drop_mut,
    exception_private::{ExcType, ExcTypeExt, RunError, RunResult, SimpleException},
    hash::HashValue,
    heap::{ContainsHeap, DropGuard, DropWithContext, HeapData, HeapId, HeapRead, HeapReadOutput},
    intern::{StaticStrings, StringId},
    modules::ModuleFunctions,
    types::{
        Class, DataclassOptions, Dict, Instance, LazyHeapSet, Module, PyTrait,
        host_class::{host_class_type, write_dataclass_repr},
        instance::{class_defines, class_dunder, class_name, instance_attr},
    },
    value::{Marker, Value},
};

/// `dataclasses` module functions — each variant is a Python-visible callable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, strum::Display, serde::Serialize, serde::Deserialize)]
#[strum(serialize_all = "snake_case")]
pub(crate) enum DataclassesFunctions {
    /// The `@dataclass` decorator.
    Dataclass,
    /// `is_dataclass(obj)` — true for a dataclass class or instance.
    IsDataclass,
    /// `field(...)` — builds the `Field` a class body binds and the decorator
    /// then adopts.
    Field,
    /// The decorator `@dataclass(...)` returns while it waits for the class,
    /// carrying the bound options so `d = dataclass(frozen=True)` then `@d`
    /// works. Named for the user-visible decorator, not the variant.
    #[strum(serialize = "dataclass")]
    Configured(DataclassOptions),
}

/// Creates the `dataclasses` module and allocates it on the heap.
pub fn create_module(vm: &mut VM<'_>) -> HeapId {
    let mut module = Module::new(StaticStrings::Dataclasses);
    module.set_attr(
        StaticStrings::Dataclass,
        Value::ModuleFunction(ModuleFunctions::Dataclasses(DataclassesFunctions::Dataclass)),
        vm,
    );
    module.set_attr(
        StaticStrings::IsDataclass,
        Value::ModuleFunction(ModuleFunctions::Dataclasses(DataclassesFunctions::IsDataclass)),
        vm,
    );
    module.set_attr(
        StaticStrings::FrozenInstanceError,
        Value::Builtin(Builtins::ExcType(ExcType::FrozenInstanceError)),
        vm,
    );
    module.set_attr(
        StaticStrings::Field,
        Value::ModuleFunction(ModuleFunctions::Dataclasses(DataclassesFunctions::Field)),
        vm,
    );
    // `MISSING` is a bare sentinel compared by identity, so it needs no state
    // beyond its name — a `Marker`, like `sys.stdout` and the `typing` forms.
    module.set_attr(
        StaticStrings::Missing,
        Value::Marker(Marker(StaticStrings::Missing)),
        vm,
    );
    vm.heap.allocate_as(module).into_id()
}

/// Dispatches a `dataclasses` module function call.
pub(super) fn call(vm: &mut VM<'_>, func: DataclassesFunctions, args: ArgValues) -> RunResult<Value> {
    match func {
        DataclassesFunctions::Dataclass => dataclass_decorator(vm, args),
        DataclassesFunctions::IsDataclass => is_dataclass(vm, args),
        DataclassesFunctions::Field => field::field(vm, args),
        // The options are already bound; this call supplies the class.
        DataclassesFunctions::Configured(options) => {
            let ConfiguredArgs { cls } = ConfiguredArgs::from_args(args, vm)?;
            apply_dataclass(vm, cls, options)
        }
    }
}

/// The `@dataclass` decorator, in both spellings: applied bare the class
/// arrives here directly, while `@dataclass(...)` has none yet and gets back a
/// [`DataclassesFunctions::Configured`] that receives it on the next call.
fn dataclass_decorator(vm: &mut VM<'_>, args: ArgValues) -> RunResult<Value> {
    let DataclassArgs {
        cls,
        init,
        repr,
        eq,
        order,
        unsafe_hash,
        frozen,
        match_args,
        kw_only,
        slots,
        weakref_slot,
    } = DataclassArgs::from_args(args, vm)?;
    // CPython's `dataclass` is a `def`, so it type-checks nothing and takes each
    // option's truthiness. That runs user code — a `__bool__` may raise — so
    // `cls` and all ten flags are guarded before the first read.
    let mut guard = DropGuard::new(
        [
            cls,
            init,
            repr,
            eq,
            order,
            unsafe_hash,
            frozen,
            match_args,
            kw_only,
            slots,
            weakref_slot,
        ],
        vm,
    );
    let (values, vm) = guard.as_parts();
    let mut truthy = [false; 10];
    for (slot, flag) in truthy.iter_mut().zip(&values[1..]) {
        *slot = flag.py_bool(vm)?;
    }
    let [
        init,
        repr,
        eq,
        order,
        unsafe_hash,
        frozen,
        match_args,
        kw_only,
        slots,
        weakref_slot,
    ] = truthy;
    let options = DataclassOptions { eq, frozen };
    // Options Monty does not implement are refused when set away from their
    // CPython default, rather than accepted and ignored.
    let unimplemented = [
        ("init", init, true),
        ("repr", repr, true),
        ("order", order, false),
        ("unsafe_hash", unsafe_hash, false),
        ("match_args", match_args, true),
        ("kw_only", kw_only, false),
        ("slots", slots, false),
        ("weakref_slot", weakref_slot, false),
    ]
    .into_iter()
    .find(|&(_, given, default)| given != default);
    // Only truthiness is kept, so the flags are released here; `cls` alone lives
    // on, into the return value.
    let (values, vm) = guard.into_parts();
    let [cls, flags @ ..] = values;
    flags.drop_with(vm);
    match unimplemented {
        Some((name, _, _)) => {
            cls.drop_with(vm);
            Err(ExcType::not_implemented(format!("dataclass() does not yet support the {name} option")).into())
        }
        // `@dataclass(...)`: no class yet, so hand back the configured decorator.
        None if matches!(cls, Value::None) => Ok(Value::ModuleFunction(ModuleFunctions::Dataclasses(
            DataclassesFunctions::Configured(options),
        ))),
        None => apply_dataclass(vm, cls, options),
    }
}

/// `@dataclass` arguments, mirroring CPython's
/// `dataclass(cls=None, /, *, init=True, repr=True, ...)`.
///
/// Raw `Value` fields because CPython's `def` type-checks nothing; the body
/// takes each option's truthiness instead.
#[derive(FromArgs)]
#[from_args(name = "dataclass", style = def)]
struct DataclassArgs {
    #[from_args(pos_only, default = Value::None)]
    cls: Value,
    #[from_args(kw_only, default = Value::Bool(true))]
    init: Value,
    #[from_args(kw_only, default = Value::Bool(true))]
    repr: Value,
    #[from_args(kw_only, default = Value::Bool(true))]
    eq: Value,
    #[from_args(kw_only, default = Value::Bool(false))]
    order: Value,
    #[from_args(kw_only, default = Value::Bool(false))]
    unsafe_hash: Value,
    #[from_args(kw_only, default = Value::Bool(false))]
    frozen: Value,
    #[from_args(kw_only, default = Value::Bool(true))]
    match_args: Value,
    #[from_args(kw_only, default = Value::Bool(false))]
    kw_only: Value,
    #[from_args(kw_only, default = Value::Bool(false))]
    slots: Value,
    #[from_args(kw_only, default = Value::Bool(false))]
    weakref_slot: Value,
}

/// The class a [`DataclassesFunctions::Configured`] decorator is waiting for.
///
/// CPython's `dataclass` closes over a plain `def wrap(cls)`, so the class binds
/// positionally *or* by keyword, and the arity errors name that closure rather
/// than `dataclass` itself. Raw `Value` for [`DataclassArgs`]' reason: a `def`
/// type-checks nothing, and `apply_dataclass` makes the class check the body
/// would.
#[derive(FromArgs)]
#[from_args(name = "dataclass.<locals>.wrap", style = def)]
struct ConfiguredArgs {
    cls: Value,
}

/// Writes `__dataclass_params__` and `__dataclass_fields__` into the class
/// namespace, and returns the class unchanged.
///
/// Ownership of `cls` passes straight through to the return value, so no extra
/// refcount work is needed on the happy path; the guard releases it on every
/// path that rejects the class instead.
fn apply_dataclass(vm: &mut VM<'_>, cls: Value, options: DataclassOptions) -> RunResult<Value> {
    let mut guard = DropGuard::new(cls, vm);
    let (cls, vm) = guard.as_parts();
    // Read once and pass the handle down: everything below then works from a
    // value already known to be a class, and the guard's reference keeps it alive.
    let Value::Ref(class_id) = cls else {
        return Err(non_class_error(cls, vm));
    };
    let HeapReadOutput::Class(mut class) = vm.heap.read(*class_id) else {
        return Err(non_class_error(cls, vm));
    };
    let fields = build_dataclass_fields(&class, vm)?;
    let Value::Ref(fields_id) = fields else {
        unreachable!("the fields mapping is a dict")
    };
    // Fields first, so nothing owns the mapping while the params allocation
    // can still fail; a class left with fields alone reads back as a default one.
    store_dataclass_fields(&mut class, fields, vm)?;
    // Now that the mapping owns them, the `field()` objects the class body left
    // as attributes can be rewritten to what CPython leaves behind.
    rewrite_field_attributes(&mut class, fields_id, vm)?;
    store_dataclass_params(&mut class, options, vm)?;
    // Last, so what the class acts on is only ever from a decoration that ran
    // to completion. `__post_init__` is decided here rather than at
    // construction: CPython bakes the call into the generated `__init__`, so a
    // hook attached to the class afterwards is never reached.
    let has_post_init = class_defines(*class_id, StaticStrings::PostInit.into(), vm);
    class.set_has_post_init(has_post_init, vm);
    class.set_dataclass_options(options, vm);
    Ok(guard.into_inner())
}

/// `dataclass()` applied to something that is not a class.
fn non_class_error(cls: &Value, vm: &VM<'_>) -> RunError {
    let type_name = cls.py_type_name(vm);
    SimpleException::new_msg(
        ExcType::TypeError,
        format!("dataclass() should be called on a class, not '{type_name}'"),
    )
    .into()
}

/// Builds the `name -> Field` mapping for `class` from its `__annotations__`:
/// the annotated names in definition order, minus `ClassVar` entries, each
/// owning the default the class namespace bound for it (`y: int = 5`).
///
/// Also where a class body Monty cannot yet honour is rejected, so an
/// unimplemented feature raises rather than producing a subtly wrong class
/// (see `limitations/dataclasses.md`). The fields are guarded throughout, so a
/// rejection releases the defaults already captured.
fn build_dataclass_fields<'h>(class: &HeapRead<'h, Class>, vm: &mut VM<'h>) -> RunResult<Value> {
    let fields = collect_annotated_fields(class, vm);
    let mut guard = DropGuard::new(fields, vm);
    let (fields, vm) = guard.as_parts();
    // Field validation runs first, so a class CPython would reject reports
    // CPython's own message and the Monty-only guards can only fire after.
    validate_fields(vm, fields)?;
    let (fields, vm) = guard.into_parts();
    allocate_fields_dict(vm, fields)
}

/// Allocates the dict `__dataclass_fields__` holds, consuming the collected
/// fields. The dict owns every `Field` from its first insertion, so a failure
/// part-way releases them with it.
fn allocate_fields_dict(vm: &mut VM<'_>, fields: Vec<Value>) -> RunResult<Value> {
    let dict = vm.heap.allocate_as(Dict::with_capacity(fields.len()));
    let mut guard = DropGuard::new(dict, vm);
    let (dict, vm) = guard.as_parts_mut();
    let dict = dict.read(vm.heap);
    for field_value in fields {
        // Consumed rather than matched: the reference moves into the dict below,
        // so the original must not also be released.
        let Some(field_id) = field_value.into_ref_id() else {
            unreachable!("collection produces only heap fields")
        };
        let name = field_at_id(vm, field_id)
            .expect("collection produces only `Field`s")
            .name()
            .expect("collection adopts every field");
        // One `field()` object bound under two names is adopted twice and keyed
        // by the second, so a replacement does happen — CPython collapses the
        // pair the same way. A dict rejected by the memory limit releases the
        // field it was handed.
        let replaced = dict.set(Value::InternString(name), Value::Ref(field_id), vm)?;
        replaced.drop_with(vm);
    }
    Ok(guard.into_inner().into_value())
}

/// Writes `__dataclass_fields__` into the class namespace, taking ownership of
/// `fields`. Re-decorating replaces the previous mapping, which nothing else
/// owns once it is out of the namespace.
fn store_dataclass_fields<'h>(class: &mut HeapRead<'h, Class>, fields: Value, vm: &mut VM<'h>) -> RunResult<()> {
    let replaced = class.set_attr(StaticStrings::DataclassFields.into(), fields, vm)?;
    replaced.drop_with(vm);
    Ok(())
}

/// Writes `__dataclass_params__` into the class namespace, as CPython's
/// `_DataclassParams` records the same options.
///
/// Purely introspection: the options the class *acts* on live on the [`Class`],
/// so overwriting this entry reports something else without changing behaviour,
/// exactly as it does in CPython.
fn store_dataclass_params<'h>(
    class: &mut HeapRead<'h, Class>,
    options: DataclassOptions,
    vm: &mut VM<'h>,
) -> RunResult<()> {
    let params = vm.heap.allocate_as(DataclassParams::new(options)).into_value();
    let replaced = class.set_attr(StaticStrings::DataclassParams.into(), params, vm)?;
    replaced.drop_with(vm);
    Ok(())
}

/// Rewrites the class attribute each `field()` left behind, as CPython does:
/// a plain default becomes the attribute, and a field with only a factory —
/// which has no single value to expose — loses it.
///
/// Runs once the fields are stored, so the mapping is the list of names to fix.
fn rewrite_field_attributes<'h>(class: &mut HeapRead<'h, Class>, fields_id: HeapId, vm: &mut VM<'h>) -> RunResult<()> {
    for (name, field_id) in adopted_field_ids(fields_id, vm) {
        // Only an attribute that *is* the field object needs rewriting; a plain
        // `x: int = 5` already binds the value CPython would leave behind.
        let bound = class
            .get(vm.heap)
            .namespace()
            .get_by_str(vm.interns.get_str(name), vm.heap, vm.interns);
        if !matches!(bound, Some(Value::Ref(id)) if *id == field_id) {
            continue;
        }
        let default = field_at_id(vm, field_id).and_then(|field| field.default().map(|v| v.clone_with_heap(vm.heap)));
        let name = Value::InternString(name);
        let replaced = match default {
            Some(default) => class.set_attr(name, default, vm)?,
            None => class.pop_attr(&name, vm)?,
        };
        replaced.drop_with(vm);
    }
    Ok(())
}

/// The `(name, field_id)` of every field in a `__dataclass_fields__` dict.
fn adopted_field_ids(fields_id: HeapId, vm: &VM<'_>) -> Vec<(StringId, HeapId)> {
    let HeapData::Dict(fields) = vm.heap.get(fields_id) else {
        return Vec::new();
    };
    fields
        .iter()
        .filter_map(|(_, value)| match value {
            Value::Ref(id) => Some((field_at_id(vm, *id)?.name()?, *id)),
            _ => None,
        })
        .collect()
}

/// Collects the dataclass fields from `__annotations__`, in definition order,
/// dropping `ClassVar` entries, as owned references to heap `Field`s.
///
/// A class-body value that is already a `field()` result is **adopted in place**
/// — the same object gains the name and annotation and goes on to
/// `__dataclass_fields__`, as CPython's decorator does — so
/// `C.__dataclass_fields__['x'] is f`. Anything else is an ordinary default and
/// gets a fresh `Field` built around it.
///
/// The returned references are owned, so a caller that discards them must
/// release them (`drop_with`).
fn collect_annotated_fields<'h>(class: &HeapRead<'h, Class>, vm: &mut VM<'h>) -> Vec<Value> {
    let names = annotated_field_names(class, vm);
    let mut guard = DropGuard::new(Vec::with_capacity(names.len()), vm);
    let (fields, vm) = guard.as_parts_mut();
    for name_id in names {
        let namespace = class.get(vm.heap).namespace();
        // Captured now, as CPython bakes it into the generated `__init__`:
        // rebinding the class attribute later must not change it.
        let bound = namespace
            .get_by_str(vm.interns.get_str(name_id), vm.heap, vm.interns)
            .map(|v| v.clone_with_heap(vm.heap));
        let annotation = field_annotation(class, name_id, vm);
        // The class body bound a `field()` result: it *is* the field, so it
        // takes the name and annotation and the list keeps that reference.
        // Anything else is a plain default, wrapped in a field of its own.
        if let Some(field_id) = adoptable_field(bound.as_ref(), vm) {
            let HeapReadOutput::DataclassField(mut field) = vm.heap.read(field_id) else {
                unreachable!("adoptable_field matched the variant")
            };
            let replaced = field.get_mut(vm.heap).adopt(name_id, annotation);
            replaced.drop_with(vm);
            fields.push(bound.expect("adoptable_field matched a bound value"));
        } else {
            let field = DataclassField::new(name_id, annotation, bound);
            fields.push(vm.heap.allocate_as(field).into_value());
        }
    }
    guard.into_parts().0
}

/// The annotated field names in definition order, minus `ClassVar` entries.
///
/// Names alone, so the collection loop can take the heap mutably instead of
/// holding a borrow of the annotations dict across an allocation.
fn annotated_field_names<'h>(class: &HeapRead<'h, Class>, vm: &VM<'h>) -> Vec<StringId> {
    let Some(annotations) = annotations_dict(class, vm) else {
        return Vec::new();
    };
    annotations
        .into_iter()
        .filter_map(|(key, annotation)| match key {
            Value::InternString(name_id) if !is_classvar(&annotation_text(annotation, vm)) => Some(*name_id),
            _ => None,
        })
        .collect()
}

/// One field's annotation, cloned as an owned reference for the `Field` to hold.
fn field_annotation<'h>(class: &HeapRead<'h, Class>, name: StringId, vm: &VM<'h>) -> Value {
    annotations_dict(class, vm)
        .and_then(|annotations| annotations.get_by_str(vm.interns.get_str(name), vm.heap, vm.interns))
        .map_or(Value::None, |annotation| annotation.clone_with_heap(vm.heap))
}

/// The class's `__annotations__` dict, or `None` for a class body with none.
fn annotations_dict<'a, 'h>(class: &HeapRead<'h, Class>, vm: &'a VM<'h>) -> Option<&'a Dict> {
    match class
        .get(vm.heap)
        .namespace()
        .get_by_str("__annotations__", vm.heap, vm.interns)
    {
        Some(Value::Ref(id)) => match vm.heap.get(*id) {
            HeapData::Dict(annotations) => Some(annotations),
            _ => None,
        },
        _ => None,
    }
}

/// A stringized annotation as text, or `""` for the non-string annotations
/// Monty never produces (it always stores annotations as source text).
fn annotation_text(annotation: &Value, vm: &VM<'_>) -> String {
    annotation
        .as_either_str(vm.heap)
        .map(|s| s.as_str(vm.interns).to_owned())
        .unwrap_or_default()
}

/// Rejects field lists Monty cannot honour, in CPython's checking order.
///
/// CPython validates defaults per field as it collects them, so a mutable
/// default is reported before the whole-list non-default-after-default check.
fn validate_fields(vm: &mut VM<'_>, fields: &[Value]) -> RunResult<()> {
    for field_value in fields {
        // Read out first: hashing a default needs the heap mutably.
        let Some((name, annotation_text, default)) = read_field(field_value, vm) else {
            continue;
        };
        defer_drop!(default, vm);
        let name = vm.interns.get_str(name).to_owned();
        if is_initvar(&annotation_text) {
            return Err(ExcType::not_implemented(format!(
                "dataclass() does not yet support InitVar (field {name}), which would become an ordinary field"
            ))
            .into());
        }
        if let Some(default) = default {
            // CPython's rule is hashability, not a list/dict/set type check, so
            // a class with `__hash__ = None` is rejected the same way. A factory
            // is exempt: it is the sanctioned way to have a mutable default.
            if default.py_hash(vm)?.is_none() {
                let ty = default.py_type_name(vm);
                return Err(ExcType::value_error(format!(
                    "mutable default <class '{ty}'> for field {name} is not allowed: use default_factory"
                )));
            }
        }
    }
    // CPython rejects the class outright rather than failing at construction.
    if let Some((prev, field)) = first_non_default_after_default(fields, vm) {
        let (prev, field) = (vm.interns.get_str(prev), vm.interns.get_str(field));
        return Err(ExcType::type_error(format!(
            "non-default argument '{field}' follows default argument '{prev}'"
        )));
    }
    Ok(())
}

/// A collected field's name, annotation text, and a **cloned** default — the
/// three things validation needs, read before it takes the heap mutably.
fn read_field(field: &Value, vm: &VM<'_>) -> Option<(StringId, String, Option<Value>)> {
    let Value::Ref(id) = field else { return None };
    let field = field_at_id(vm, *id)?;
    let annotation = field.annotation().map_or_else(String::new, |a| annotation_text(a, vm));
    Some((
        field.name().expect("collection adopts every field"),
        annotation,
        field.default().map(|d| d.clone_with_heap(vm.heap)),
    ))
}

/// The first `(defaulted, non_defaulted)` field pair that would produce an
/// invalid `__init__` signature, or `None` when the order is valid.
///
/// A `default_factory` counts as a default, as it does in CPython's generated
/// signature.
fn first_non_default_after_default(fields: &[Value], vm: &VM<'_>) -> Option<(StringId, StringId)> {
    let mut last_default = None;
    fields.iter().find_map(|field| {
        let Value::Ref(id) = field else { return None };
        let field = field_at_id(vm, *id)?;
        let name = field.name().expect("collection adopts every field");
        match (field.has_default(), last_default) {
            (true, _) => {
                last_default = Some(name);
                None
            }
            (false, Some(prev)) => Some((prev, name)),
            (false, None) => None,
        }
    })
}

/// Whether a stringized annotation denotes `typing.ClassVar`, so the field is
/// excluded.
///
/// Detection is textual where CPython resolves the annotation through the
/// defining module, so neither the import nor a dotted spelling's module is
/// checked — both divergences are in `limitations/dataclasses.md`.
fn is_classvar(annotation: &str) -> bool {
    annotation_head(annotation, "ClassVar")
}

/// Whether a stringized annotation denotes `dataclasses.InitVar`. Matched the
/// same way as [`is_classvar`], and with the same textual-only caveats.
fn is_initvar(annotation: &str) -> bool {
    annotation_head(annotation, "InitVar")
}

/// Whether a stringized annotation names `name`, bare, subscripted, or
/// dotted (`typing.ClassVar[int]`), ignoring surrounding whitespace and quotes.
///
/// Quotes must be stripped because a quoted annotation (`x: "ClassVar[int]"`)
/// is stringized with its quotes intact. The subscript is split off before the
/// qualifier check so a dotted type argument (`ClassVar[a.b]`) still matches.
fn annotation_head(annotation: &str, name: &str) -> bool {
    let s = annotation.trim().trim_matches(|c| c == '\'' || c == '"').trim();
    let head = s.split_once('[').map_or(s, |(head, _)| head).trim_end();
    head.rsplit('.').next() == Some(name)
}

/// The `__dataclass_fields__` dict a class namespace holds, or `None` when the
/// class is not a dataclass.
///
/// Every reader goes through the namespace, so a class whose
/// `__dataclass_fields__` sandboxed code overwrote simply stops being a
/// dataclass rather than reading metadata the class no longer advertises.
fn fields_dict_id(namespace: &Dict, vm: &VM<'_>) -> Option<HeapId> {
    match namespace.get_by_str(StaticStrings::DataclassFields.into(), vm.heap, vm.interns) {
        Some(Value::Ref(id)) if matches!(vm.heap.get(*id), HeapData::Dict(_)) => Some(*id),
        _ => None,
    }
}

/// [`fields_dict_id`] for the callers holding only a class `HeapId` — the
/// generic `Instance` code, which reaches a class through its instance.
fn class_fields_dict_id(class_id: HeapId, vm: &VM<'_>) -> Option<HeapId> {
    match vm.heap.get(class_id) {
        HeapData::Class(class) => fields_dict_id(class.namespace(), vm),
        _ => None,
    }
}

/// The options `@dataclass` recorded on `class_id`, or `None` for a class that
/// is not a dataclass — the split the `Instance` dunders branch on.
///
/// Still gated on the fields, which stay the mark of a dataclass: overwriting
/// `__dataclass_fields__` un-marks the class, as it does for `is_dataclass`.
pub(crate) fn dataclass_options(class_id: HeapId, vm: &VM<'_>) -> Option<DataclassOptions> {
    let HeapData::Class(class) = vm.heap.get(class_id) else {
        return None;
    };
    fields_dict_id(class.namespace(), vm)?;
    Some(class.dataclass_options())
}

/// The `__hash__` a `@dataclass` decoration generates, where it generates one.
///
/// The cells of CPython's `_hash_action` table that write a `__hash__`; every
/// other cell leaves the class to its own body, which [`hash_action`] reports as
/// `None`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum DataclassHash {
    /// CPython's `_hash_add`: hash by the field values, as a tuple of them does.
    FieldWise,
    /// CPython's `_hash_set_none`: value equality without immutability.
    Unhashable,
}

/// Which [`DataclassHash`] `class_id`'s decoration generated, or `None` when
/// CPython would leave the class's own `__hash__` standing — including for a
/// plain class, which is most callers' path.
///
/// Monty refuses `unsafe_hash`, so CPython's four-way table collapses to `eq`,
/// `frozen`, and whether the body set a `__hash__` of its own.
pub(crate) fn hash_action(class_id: HeapId, vm: &VM<'_>) -> Option<DataclassHash> {
    let options = dataclass_options(class_id, vm)?;
    // CPython's `has_explicit_hash`: a `__hash__ = None` beside a body `__eq__`
    // is the opt-out `type` inserted, not one the author wrote, so a generated
    // hash overwrites it. Alone, it is deliberate and survives.
    let explicit_hash = class_dunder(class_id, "__hash__", vm)
        .is_some_and(|hash| !(matches!(hash, Value::None) && class_defines(class_id, "__eq__", vm)));
    match (options.eq, options.frozen, explicit_hash) {
        (true, true, false) => Some(DataclassHash::FieldWise),
        (true, false, false) => Some(DataclassHash::Unhashable),
        _ => None,
    }
}

/// The error assigning `name` raises on a `frozen=True` dataclass instance, or
/// `None` when the write may proceed.
///
/// Every instance assignment passes through here, so it reads the class's
/// options alone: only a decoration sets them, so [`dataclass_options`]' field
/// lookup would be redundant work on this path.
pub(crate) fn frozen_assignment_error(class_id: HeapId, name: &Value, vm: &VM<'_>) -> Option<RunError> {
    let HeapData::Class(class) = vm.heap.get(class_id) else {
        return None;
    };
    if !class.dataclass_options().frozen {
        return None;
    }
    // Refused for any attribute, declared field or not, as CPython's generated
    // `__setattr__` does.
    let message = match name.as_either_str(vm.heap) {
        Some(field) => format!("cannot assign to field '{}'", field.as_str(vm.interns)),
        None => "cannot assign to field".to_owned(),
    };
    Some(SimpleException::new_msg(ExcType::FrozenInstanceError, message).into())
}

/// Dataclass field names in definition order, or `None` for a plain class —
/// the `Some`/`None` split the generic `Instance` code branches on.
pub(crate) fn dataclass_fields(class_id: HeapId, vm: &VM<'_>) -> Option<Vec<StringId>> {
    let fields_id = class_fields_dict_id(class_id, vm)?;
    Some(field_specs(fields_id, vm).into_iter().map(|(name, _)| name).collect())
}

/// Each field's `(name, has_default)`, in definition order — everything
/// `bind_dataclass_fields` needs once the heap borrow is released.
///
/// A `default_factory` counts as a default: the parameter is optional, and the
/// factory runs when nothing is bound to it.
fn field_specs(fields_id: HeapId, vm: &VM<'_>) -> Vec<(StringId, bool)> {
    let HeapData::Dict(fields) = vm.heap.get(fields_id) else {
        return Vec::new();
    };
    fields
        .iter()
        .filter_map(|(_, value)| match value {
            Value::Ref(id) => {
                let field = field_at_id(vm, *id)?;
                Some((field.name()?, field.has_default()))
            }
            _ => None,
        })
        .collect()
}

/// Whether `class_id` names a dataclass, when the field names aren't needed.
pub(crate) fn is_dataclass_class(class_id: HeapId, vm: &VM<'_>) -> bool {
    class_fields_dict_id(class_id, vm).is_some()
}

/// Constructs a dataclass instance by binding `args` to the recorded fields,
/// taking ownership of the freshly allocated `instance`.
///
/// No bytecode is generated: arguments bind natively as CPython's synthesized
/// `__init__(self, f1, f2=default, ...)` would, filling unbound fields from the
/// defaults captured at decoration time. Drops the instance on error.
pub(crate) fn dataclass_init<'h>(
    vm: &mut VM<'h>,
    class: &HeapRead<'h, Class>,
    instance: Value,
    args: ArgValues,
) -> Result<CallResult, RunError> {
    let fields_id =
        fields_dict_id(class.get(vm.heap).namespace(), vm).expect("dataclass_init requires __dataclass_fields__");
    // Owned field metadata (name + has-default), releasing the heap borrow.
    let fields = field_specs(fields_id, vm);

    // The instance is owned from here: the guard releases it if binding or
    // storing fails, and hands it back to the caller when they succeed.
    let mut guard = DropGuard::new(instance, vm);
    let (instance, vm) = guard.as_parts();
    // Read once for the whole construction. The handle is declared after the
    // guard so it is released first — a guard that frees the instance must not
    // find a live reader.
    let Value::Ref(instance_id) = instance else {
        unreachable!("the caller just allocated the instance")
    };
    let HeapReadOutput::Instance(mut instance) = vm.heap.read(*instance_id) else {
        unreachable!("the caller just allocated the instance")
    };
    let values = bind_dataclass_fields(vm, class, fields_id, &fields, args)?;
    store_bound_fields(&mut instance, &fields, values, vm)?;
    run_post_init(*instance_id, class, vm)?;
    Ok(CallResult::Value(guard.into_inner()))
}

/// Calls the class's `__post_init__` once every field is stored, as CPython's
/// generated `__init__` ends by doing.
///
/// Runs through [`VM::evaluate_function`], like a `default_factory`, so it
/// cannot suspend on an external or OS call where a hand-written `__init__`
/// can — documented in `limitations/dataclasses.md`. Its return value is
/// discarded, and anything it raises propagates out of the constructor, leaving
/// the half-built instance to the caller's guard.
fn run_post_init<'h>(instance_id: HeapId, class: &HeapRead<'h, Class>, vm: &mut VM<'h>) -> RunResult<()> {
    if !class.get(vm.heap).has_post_init() {
        return Ok(());
    }
    // Read as an attribute, so the method arrives bound to the instance.
    let Some(post_init) = instance_attr(instance_id, StaticStrings::PostInit.into(), vm) else {
        return Ok(());
    };
    defer_drop!(post_init, vm);
    let result = vm.evaluate_function("__post_init__", post_init, ArgValues::Empty)?;
    result.drop_with(vm);
    Ok(())
}

/// Stores one bound value per field on the instance `__dict__`, consuming
/// `values`. A set failure (a resource limit) leaves the untouched tail to the
/// guard; the caller owns the instance.
fn store_bound_fields<'h>(
    instance: &mut HeapRead<'h, Instance>,
    fields: &[(StringId, bool)],
    values: Vec<Value>,
    vm: &mut VM<'h>,
) -> Result<(), RunError> {
    defer_drop_mut!(values, vm);
    for i in 0..values.len() {
        let value = mem::replace(&mut values[i], Value::None);
        let name = Value::InternString(fields[i].0);
        // Unchecked: a `frozen=True` instance refuses its own `set_attr`, as
        // CPython's generated `__init__` goes through `object.__setattr__`.
        let replaced = instance.set_attr_unchecked(name, value, vm)?;
        replaced.drop_with(vm);
    }
    Ok(())
}

/// Binds `args` to one value per dataclass field, in field order.
///
/// Bound arguments are guarded, so an error on any path releases them and the
/// unbound ones alike. The instance is untouched; the caller owns it.
///
/// Every key is a string here: `**` unpacking is the only way a non-string one
/// could arrive, and `DictMerge` raises `keywords must be strings` while
/// building the call's kwargs — before any binder runs, as CPython does.
///
/// TODO(dataclass-keywords): a third binder alongside `args::bind_native` and
/// `args::bind_python`, all three reproducing CPython's error wording and able
/// to drift. Fold into `Signature::bind` when the `@dataclass(...)` keyword form
/// lands — not a drop-in, as that fills a `&mut Vec<Value>` from `&[Value]`
/// defaults where this needs owned clones of the captured ones.
fn bind_dataclass_fields<'h>(
    vm: &mut VM<'h>,
    class: &HeapRead<'h, Class>,
    fields_id: HeapId,
    fields: &[(StringId, bool)],
    args: ArgValues,
) -> Result<Vec<Value>, RunError> {
    let n_fields = fields.len();
    let init_name = format!("{}.__init__", class.get(vm.heap).name().as_str(vm.interns));
    let (pos_iter, kwargs) = args.into_parts();

    // Every bound argument lands in `values`, guarded so each error below is a
    // plain `?` — nothing else holds an owned reference across them.
    let values: Vec<Option<Value>> = (0..n_fields).map(|_| None).collect();
    let mut guard = DropGuard::new(values, vm);
    let (values, vm) = guard.as_parts_mut();

    // Positionals fill the leftmost slots; one beyond the last field is dropped
    // here and only counted, since CPython binds keywords first: `P(1, 2, 3,
    // y=4)` is "multiple values for argument 'y'", not an arity error.
    let mut n_pos = 0;
    for (slot, value) in pos_iter.enumerate() {
        n_pos += 1;
        match values.get_mut(slot) {
            Some(unbound) => *unbound = Some(value),
            None => value.drop_with(vm),
        }
    }

    bind_keyword_args(values, fields, kwargs, &init_name, vm)?;

    // Too many positionals (CPython counts `self`, so +1 each side), reported
    // only once keyword binding has had its say.
    if n_pos > n_fields {
        let required = fields.iter().filter(|(_, has_default)| !has_default).count();
        return Err(ExcType::type_error_too_many_positional_range(
            &init_name,
            1 + required,
            1 + n_fields,
            1 + n_pos,
            0,
        ));
    }

    // Everything the unbound slots need, read out as owned values before a
    // single factory runs. Past this point nothing resolves `fields_id`, so a
    // factory that replaces `__dataclass_fields__` cannot leave the loop
    // reading a freed dict — nor shift a later field's default.
    let plan = snapshot_field_inits(vm, fields_id, values);
    let mut plan_guard = DropGuard::new(plan, vm);
    let (plan, vm) = plan_guard.as_parts_mut();

    // Reported before any factory runs, as CPython's argument binding raises
    // before the generated `__init__` body — and therefore its factories — ever
    // executes.
    let missing: Vec<String> = plan
        .iter()
        .enumerate()
        .filter(|(idx, init)| values[*idx].is_none() && matches!(init, FieldInit::Unsupplied))
        .map(|(idx, _)| vm.interns.get_str(fields[idx].0).to_owned())
        .collect();
    if !missing.is_empty() {
        let refs: Vec<&str> = missing.iter().map(String::as_str).collect();
        return Err(ExcType::type_error_missing_positional_with_names(&init_name, &refs));
    }

    // Factories run in field order, and only for a field left unbound. Each
    // entry is taken out of the plan as it is used, so an error part-way leaves
    // the guard only the ones still to come.
    for idx in 0..plan.len() {
        if values[idx].is_some() {
            continue;
        }
        values[idx] = Some(match mem::replace(&mut plan[idx], FieldInit::Unsupplied) {
            FieldInit::Default(default) => default,
            FieldInit::Factory(factory) => {
                defer_drop!(factory, vm);
                vm.evaluate_function("dataclass field default_factory", factory, ArgValues::Empty)?
            }
            FieldInit::Unsupplied => unreachable!("the missing check rejected every unsupplied field"),
        });
    }
    drop(plan_guard);

    Ok(guard
        .into_inner()
        .into_iter()
        .map(|v| v.expect("all fields bound"))
        .collect())
}

/// Fills the named slots of `values` from the keyword arguments.
///
/// The iterator is guarded, so an error mid-mapping raises on the spot and the
/// pairs it never reached are still released. Keys are known to be strings —
/// the caller rejects a non-string one before any binding happens.
fn bind_keyword_args(
    values: &mut [Option<Value>],
    fields: &[(StringId, bool)],
    kwargs: KwargsValues,
    init_name: &str,
    vm: &mut VM<'_>,
) -> RunResult<()> {
    let kwargs = kwargs.into_iter();
    defer_drop_mut!(kwargs, vm);
    for (key, value) in kwargs.by_ref() {
        defer_drop!(key, vm);
        let name = key
            .as_either_str(vm.heap)
            .expect("DictMerge rejects non-string keys before the call")
            .as_str(vm.interns)
            .to_owned();
        // Resolved before the value is guarded, which borrows the VM.
        let slot = fields.iter().position(|(id, _)| vm.interns.get_str(*id) == name);
        let value = DropGuard::new(value, vm);
        match slot {
            Some(idx) if values[idx].is_none() => values[idx] = Some(value.into_inner()),
            Some(_) => return Err(ExcType::type_error_duplicate_arg(init_name, &name)),
            None => return Err(ExcType::type_error_unexpected_keyword(init_name, &name)),
        }
    }
    Ok(())
}

/// What the synthesized `__init__` supplies for a field the call left unbound.
///
/// Snapshotted as owned values before any of it is used, because running a
/// `default_factory` re-enters the VM: sandbox code there can rebind
/// `__dataclass_fields__`, freeing the dict the plan was read from.
enum FieldInit {
    /// Nothing to supply — either the call bound the field, or it has no
    /// default and no factory. The missing-argument check separates the two.
    Unsupplied,
    /// The default captured at decoration, cloned for this construction.
    Default(Value),
    /// The `default_factory` callable, to be called once for this construction.
    Factory(Value),
}

impl<C: ContainsHeap> DropWithContext<C> for FieldInit {
    fn drop_with(self, ctx: &mut C) {
        match self {
            Self::Unsupplied => {}
            Self::Default(value) | Self::Factory(value) => value.drop_with(ctx),
        }
    }
}

/// Reads every unbound field's default or factory out of `fields_id` as owned
/// references, in field order.
///
/// The one place the fields mapping is read during construction, and it runs
/// before anything can re-enter the VM — see [`FieldInit`]. A slot the call
/// already bound is skipped, so a construction that supplies every argument
/// clones nothing.
fn snapshot_field_inits(vm: &VM<'_>, fields_id: HeapId, values: &[Option<Value>]) -> Vec<FieldInit> {
    values
        .iter()
        .enumerate()
        .map(|(idx, bound)| match (bound, field_at(vm, fields_id, idx)) {
            (Some(_), _) | (_, None) => FieldInit::Unsupplied,
            (None, Some(field)) => match (field.default(), field.default_factory()) {
                (Some(default), _) => FieldInit::Default(default.clone_with_heap(vm.heap)),
                (None, Some(factory)) => FieldInit::Factory(factory.clone_with_heap(vm.heap)),
                (None, None) => FieldInit::Unsupplied,
            },
        })
        .collect()
}

/// Field-wise `__eq__`: equal only to the *same* dataclass with equal fields.
/// Any other operand is `NotImplemented` (`Ok(None)`), leaving the caller on
/// identity.
///
/// Mirrors CPython 3.14's generated `self.a == other.a and self.b == other.b` —
/// left to right, stopping at the first unequal pair, each compared with the
/// `==` *operator* rather than container equality.
pub(crate) fn dataclass_eq(
    self_id: HeapId,
    field_names: &[StringId],
    other: &Value,
    vm: &mut VM<'_>,
) -> RunResult<Option<bool>> {
    let class_id = instance_class(self_id, vm);
    // Only the same dataclass type can be equal; otherwise NotImplemented.
    let &Value::Ref(other_id) = other else {
        return Ok(None);
    };
    if !matches!(vm.heap.get(other_id), HeapData::Instance(inst) if inst.class() == class_id) {
        return Ok(None);
    }
    // Charge a recursion level: two distinct cyclic dataclasses (`a.x = a;
    // b.x = b; a == b`) re-enter here per level and would otherwise overflow
    // the host stack.
    let mut guard = vm.recursion_guard()?;
    let vm = &mut *guard;
    for name_id in field_names {
        let field_name = vm.interns.get_str(*name_id).to_owned();
        // Both reads are guarded so a failing comparison below (or an early
        // return) cannot strand either value.
        let a = instance_attr(self_id, &field_name, vm);
        defer_drop!(a, vm);
        let b = instance_attr(other_id, &field_name, vm);
        defer_drop!(b, vm);
        match (a, b) {
            (Some(a), Some(b)) if !a.py_eq_operator(b, vm)? => return Ok(Some(false)),
            (Some(_), Some(_)) => {}
            // The generated `__eq__` reads each field as an attribute, so one
            // that resolves nowhere raises rather than comparing unequal.
            _ => {
                let class_name = class_name(class_id, vm.heap, vm.interns).into_owned();
                return Err(ExcType::attribute_error(&class_name, &field_name));
            }
        }
    }
    Ok(Some(true))
}

/// Synthesized `__hash__` for a `frozen=True` dataclass: the hash of the field
/// values as a tuple, matching CPython's generated `hash((self.f1, ...))`.
///
/// An unhashable field raises naming *its* type, as hashing that tuple would;
/// fields are read as attributes, as the generated `__hash__` reads them, so an
/// uninitialised one raises too.
pub(crate) fn dataclass_hash(self_id: HeapId, field_names: &[StringId], vm: &mut VM<'_>) -> RunResult<HashValue> {
    let class_id = instance_class(self_id, vm);
    // Charge a recursion level, as `dataclass_eq` does: a frozen class cannot
    // build a cycle itself, but options are read live, so retro-freezing a class
    // whose instances already cycle (`C.__dataclass_params__ = Frozen...`) would
    // otherwise re-enter here per level and overflow the host stack.
    let mut guard = vm.recursion_guard()?;
    let vm = &mut *guard;
    // Same walk as `Tuple::py_hash`, so `hash(Point(1, 2)) == hash((1, 2))`.
    let mut hasher = DefaultHasher::new();
    for name_id in field_names {
        let field_name = vm.interns.get_str(*name_id).to_owned();
        let value = instance_attr(self_id, &field_name, vm);
        defer_drop!(value, vm);
        let Some(value) = value else {
            let class_name = class_name(class_id, vm.heap, vm.interns).into_owned();
            return Err(ExcType::attribute_error(&class_name, &field_name));
        };
        match value.py_hash(vm)? {
            Some(h) => h.hash(&mut hasher),
            None => return Err(ExcType::type_error_unhashable(&value.py_type_name(vm))),
        }
    }
    Ok(HashValue::new(hasher.finish()))
}

/// Synthesized `__repr__`: `ClassName(f1=v1, ...)`. Formatting is shared with
/// the host-supplied `Dataclass` via [`write_dataclass_repr`] so the two cannot
/// drift.
pub(crate) fn dataclass_repr_fmt(
    self_id: HeapId,
    field_names: &[StringId],
    f: &mut impl Write,
    vm: &mut VM<'_>,
    heap_ids: &mut LazyHeapSet,
) -> RunResult<()> {
    let class_id = instance_class(self_id, vm);
    let name = class_name(class_id, vm.heap, vm.interns).to_string();
    // Each field is read as an attribute at the point it is written, so a field
    // whose `__repr__` mutates a later one is observed, exactly as CPython's
    // generated f-string does. A field that resolves nowhere raises.
    write_dataclass_repr(f, &name, field_names.len(), vm, heap_ids, |i, vm| {
        let field_name = vm.interns.get_str(field_names[i]).to_owned();
        match instance_attr(self_id, &field_name, vm) {
            Some(value) => Ok((field_name, Some(value))),
            None => Err(ExcType::attribute_error(&name, &field_name)),
        }
    })
}

/// Returns the `HeapId` of a dataclass instance's class object.
///
/// # Panics
/// If `self_id` is not an `Instance` — being one is how the caller chose this
/// dispatch in the first place.
fn instance_class(self_id: HeapId, vm: &VM<'_>) -> HeapId {
    match vm.heap.get(self_id) {
        HeapData::Instance(inst) => inst.class(),
        _ => unreachable!("dataclass dispatch on a non-instance"),
    }
}

/// `is_dataclass(obj)` — true when `obj` is a dataclass **class** or an
/// **instance** of one (matching CPython, which accepts both).
fn is_dataclass(vm: &mut VM<'_>, args: ArgValues) -> RunResult<Value> {
    let arg = args.get_one_arg("is_dataclass", vm.heap)?;
    let result = match &arg {
        Value::Ref(id) => match vm.heap.get(*id) {
            HeapData::Class(_) => is_dataclass_class(*id, vm),
            HeapData::Instance(instance) => is_dataclass_class(instance.class(), vm),
            // Host-backed instances and classes carry dataclass-ness as a flag
            // set by the host when the class crossed the wire.
            HeapData::HostClass(hc) => host_class_type(vm.heap, hc.class_id()).is_dataclass(),
            HeapData::HostClassType(ty) => ty.is_dataclass(),
            _ => false,
        },
        _ => false,
    };
    arg.drop_with(vm);
    Ok(Value::Bool(result))
}
