// @generated by `make generate-proto` — DO NOT EDIT.

/// Exercises every repeated field in the schema.
#[test]
fn every_schema_repeated_field_is_budgeted() {
    check_repeated(
        "monty.v1.ObjectList.items",
        1,
        WireType::LengthDelimited,
        &[18, 0],
        |message: &pb::ObjectList| &message.items,
    );
    check_repeated(
        "monty.v1.Dict.pairs",
        1,
        WireType::LengthDelimited,
        &[10, 2, 18, 0, 18, 2, 18, 0],
        |message: &pb::Dict| &message.pairs,
    );
    check_repeated(
        "monty.v1.NamedTuple.field_names",
        2,
        WireType::LengthDelimited,
        &[],
        |message: &pb::NamedTuple| &message.field_names,
    );
    check_repeated(
        "monty.v1.NamedTuple.values",
        3,
        WireType::LengthDelimited,
        &[18, 0],
        |message: &pb::NamedTuple| &message.values,
    );
    check_repeated(
        "monty.v1.RaisedException.traceback",
        3,
        WireType::LengthDelimited,
        &[],
        |message: &pb::RaisedException| &message.traceback,
    );
    check_repeated(
        "monty.v1.Feed.inputs",
        2,
        WireType::LengthDelimited,
        &[],
        |message: &pb::Feed| &message.inputs,
    );
    check_repeated(
        "monty.v1.ResumeFutures.results",
        1,
        WireType::LengthDelimited,
        &[],
        |message: &pb::ResumeFutures| &message.results,
    );
    check_repeated(
        "monty.v1.InstallDependencies.requirements",
        1,
        WireType::LengthDelimited,
        &[],
        |message: &pb::InstallDependencies| &message.requirements,
    );
    check_repeated(
        "monty.v1.Print.segments",
        3,
        WireType::LengthDelimited,
        &[],
        |message: &pb::Print| &message.segments,
    );
    check_repeated(
        "monty.v1.FunctionCall.args",
        2,
        WireType::LengthDelimited,
        &[18, 0],
        |message: &WireFunctionCall| &message.args,
    );
    check_repeated(
        "monty.v1.FunctionCall.kwargs",
        3,
        WireType::LengthDelimited,
        &[10, 2, 18, 0, 18, 2, 18, 0],
        |message: &WireFunctionCall| &message.kwargs,
    );
    check_repeated(
        "monty.v1.ResolveFutures.pending_call_ids",
        1,
        WireType::Varint,
        &[0],
        |message: &pb::ResolveFutures| &message.pending_call_ids,
    );
}
