//! Implementation of Python's `dataclasses` module.
//!
//! Native, in-sandbox `@dataclass`: the decorator records [`DataclassMeta`] on
//! the target [`Class`](crate::types::Class) and the dunders are synthesized off
//! that metadata — no `exec`, no generated bytecode. This module owns the whole
//! feature; the generic machinery calls in through narrow hooks in
//! `bytecode::vm::call` (construction) and `types::instance` (value dunders).
//!
//! See `limitations/dataclasses.md` for divergences from CPython.

use std::{fmt::Write, mem};

use monty_types::ResourceError;

use crate::{
    args::ArgValues,
    bytecode::{CallResult, VM},
    defer_drop,
    exception_private::{ExcType, ExcTypeExt, RunError, RunResult, SimpleException},
    heap::{DropWithContext, HeapData, HeapId, HeapRead, HeapReadOutput, HeapReader},
    intern::{Interns, StaticStrings, StringId},
    modules::ModuleFunctions,
    types::{
        DataclassField, DataclassMeta, Instance, LazyHeapSet, Module,
        dataclass::write_dataclass_repr,
        instance::{class_defines, class_name},
    },
    value::Value,
};

/// `dataclasses` module functions — each variant is a Python-visible callable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, strum::Display, serde::Serialize, serde::Deserialize)]
#[strum(serialize_all = "snake_case")]
pub(crate) enum DataclassesFunctions {
    /// The `@dataclass` decorator.
    Dataclass,
    /// `is_dataclass(obj)` — true for a dataclass class or instance.
    IsDataclass,
}

/// Creates the `dataclasses` module and allocates it on the heap.
pub fn create_module(vm: &mut VM<'_>) -> Result<HeapId, ResourceError> {
    let mut module = Module::new(StaticStrings::Dataclasses);
    module.set_attr(
        StaticStrings::Dataclass,
        Value::ModuleFunction(ModuleFunctions::Dataclasses(DataclassesFunctions::Dataclass)),
        vm,
    );
    module.set_attr(
        StaticStrings::IsDataclass,
        Value::ModuleFunction(ModuleFunctions::Dataclasses(DataclassesFunctions::IsDataclass)),
        vm,
    );
    vm.heap.allocate(HeapData::Module(module))
}

/// Dispatches a `dataclasses` module function call.
pub(super) fn call(vm: &mut VM<'_>, func: DataclassesFunctions, args: ArgValues) -> RunResult<Value> {
    match func {
        DataclassesFunctions::Dataclass => dataclass_decorator(vm, args),
        DataclassesFunctions::IsDataclass => is_dataclass(vm, args),
    }
}

/// The `@dataclass` decorator (bare form): records [`DataclassMeta`] on the class
/// and returns it. `@dataclass(...)` with keyword options is not yet handled.
///
/// Ownership of the single argument (the class) passes straight through to the
/// return value, so no extra refcount work is needed on the happy path.
fn dataclass_decorator(vm: &mut VM<'_>, args: ArgValues) -> RunResult<Value> {
    // `@dataclass(...)`: name the unimplemented keyword form rather than letting
    // the bare decorator's arity check report a confusing "0 given".
    if matches!(args, ArgValues::Kwargs(_) | ArgValues::ArgsKargs { .. }) {
        args.drop_with(vm);
        return Err(ExcType::type_error(
            "dataclass() keyword options (eq, order, frozen, unsafe_hash, ...) are not yet supported",
        ));
    }
    let cls = args.get_one_arg("dataclass", vm.heap)?;
    // Match by reference so `cls` is not consumed — its reference is returned
    // intact on the happy path (the decorator returns the same class object).
    let class_id = match &cls {
        Value::Ref(id) if matches!(vm.heap.get(*id), HeapData::Class(_)) => *id,
        _ => {
            let type_name = cls.py_type_name(vm);
            cls.drop_with(vm);
            return Err(SimpleException::new_msg(
                ExcType::TypeError,
                format!("dataclass() should be called on a class, not '{type_name}'"),
            )
            .into());
        }
    };
    // Extract fields from `__annotations__`, then record the metadata. On a
    // rejected class body the decorator's own reference must not leak.
    let meta = match build_dataclass_meta(vm, class_id) {
        Ok(meta) => meta,
        Err(err) => {
            cls.drop_with(vm);
            return Err(err);
        }
    };
    // Decoration grows the `Class` in place, after its allocation-time size was
    // taken, so the metadata has to be charged explicitly.
    if let Err(err) = vm.heap.track_growth(meta.estimate_size()) {
        drop_captured_defaults(meta, vm);
        cls.drop_with(vm);
        return Err(err.into());
    }
    let replaced = HeapReader::with(vm.heap, &mut (), |heap, ()| match heap.read(class_id) {
        HeapReadOutput::Class(mut class) => class.get_mut(heap).set_dataclass_meta(meta),
        _ => None,
    });
    // Re-decorating discards the earlier metadata, which nothing else owns.
    if let Some(replaced) = replaced {
        vm.heap.track_shrink(replaced.estimate_size());
        drop_captured_defaults(replaced, vm);
    }
    Ok(cls)
}

/// Releases every default a [`DataclassMeta`] captured, for metadata that is
/// being discarded rather than stored on a class.
fn drop_captured_defaults(meta: DataclassMeta, vm: &mut VM<'_>) {
    for field in meta.fields {
        if let Some(default) = field.default {
            default.drop_with(vm);
        }
    }
}

/// Builds [`DataclassMeta`] for `class_id` from its `__annotations__`.
///
/// Fields are the annotated names in definition order, excluding `ClassVar`
/// entries. A field has a default when the class namespace binds its name (i.e.
/// `y: int = 5` created a class variable); that value is captured here and owned
/// by the metadata from then on.
///
/// Also where a class body Monty cannot yet honour is rejected, so an
/// unimplemented feature raises rather than producing a subtly wrong class
/// (see `limitations/dataclasses.md`).
fn build_dataclass_meta(vm: &mut VM<'_>, class_id: HeapId) -> RunResult<DataclassMeta> {
    // Field validation runs first so that any class CPython would reject reports
    // CPython's own message; the Monty-only guards below can then only fire for
    // a class CPython accepts.
    let fields = collect_annotated_fields(vm, class_id);
    // `fields` owns a reference per captured default: release them if rejected.
    let meta = DataclassMeta { fields };
    match validate_fields(vm, &meta.fields).and_then(|()| reject_unsupported_members(vm, class_id)) {
        Ok(()) => Ok(meta),
        Err(e) => {
            drop_captured_defaults(meta, vm);
            Err(e)
        }
    }
}

/// Class-body members Monty does not dispatch, paired with what ignoring them
/// would cost. Refused rather than quietly built wrong; delete an entry once
/// its dispatch lands.
const UNSUPPORTED_MEMBERS: [(&str, &str); 1] = [("__post_init__", "which would be silently skipped")];

/// Rejects a class body defining any of [`UNSUPPORTED_MEMBERS`].
fn reject_unsupported_members(vm: &VM<'_>, class_id: HeapId) -> RunResult<()> {
    match UNSUPPORTED_MEMBERS
        .iter()
        .find(|&&(name, _)| class_defines(class_id, name, vm))
    {
        Some((name, consequence)) => Err(ExcType::type_error(format!(
            "dataclass() does not yet support {name} in a class body, {consequence}"
        ))),
        None => Ok(()),
    }
}

/// Collects the dataclass fields from `__annotations__`, in definition order.
///
/// `ClassVar` entries are dropped here; every other annotated name becomes a
/// field. Holds only immutable heap borrows and returns no heap references, so
/// the caller is free to take `&mut VM` for the validation pass.
fn collect_annotated_fields(vm: &VM<'_>, class_id: HeapId) -> Vec<DataclassField> {
    let HeapData::Class(class) = vm.heap.get(class_id) else {
        return Vec::new();
    };
    let namespace = class.namespace();
    let ann_id = match namespace.get_by_str("__annotations__", vm.heap, vm.interns) {
        Some(Value::Ref(id)) => *id,
        _ => return Vec::new(),
    };
    let HeapData::Dict(annotations) = vm.heap.get(ann_id) else {
        return Vec::new();
    };
    let mut fields = Vec::new();
    for (key, annotation) in annotations {
        // Annotation keys are always interned field-name strings.
        let Value::InternString(name_id) = key else { continue };
        let annotation = annotation
            .as_either_str(vm.heap)
            .map(|s| s.as_str(vm.interns).to_owned())
            .unwrap_or_default();
        // `ClassVar[...]` entries are class variables, not dataclass fields.
        if is_classvar(&annotation) {
            continue;
        }
        // Captured now, as CPython bakes it into the generated `__init__`:
        // rebinding the class attribute later must not change it.
        let default = namespace
            .get_by_str(vm.interns.get_str(*name_id), vm.heap, vm.interns)
            .map(|v| v.clone_with_heap(vm.heap));
        fields.push(DataclassField {
            name: *name_id,
            default,
            initvar: is_initvar(&annotation),
        });
    }
    fields
}

/// Rejects field lists Monty cannot honour, in CPython's checking order.
///
/// CPython validates defaults per field as it collects them, so a mutable
/// default is reported before the whole-list non-default-after-default check.
fn validate_fields(vm: &mut VM<'_>, fields: &[DataclassField]) -> RunResult<()> {
    for field in fields {
        let name = vm.interns.get_str(field.name).to_owned();
        if field.initvar {
            return Err(ExcType::type_error(format!(
                "dataclass() does not yet support InitVar (field {name}), which would become an ordinary field"
            )));
        }
        if let Some(default) = &field.default {
            // CPython's rule is hashability, not a list/dict/set type check, so
            // a class with `__hash__ = None` is rejected the same way. Borrowed,
            // not consumed — `build_dataclass_meta` releases it on rejection.
            if default.py_hash(vm)?.is_none() {
                let ty = default.py_type_name(vm);
                return Err(ExcType::value_error(format!(
                    "mutable default <class '{ty}'> for field {name} is not allowed: use default_factory"
                )));
            }
        }
    }
    // CPython rejects the class outright rather than failing at construction.
    if let Some((prev, field)) = first_non_default_after_default(fields) {
        let (prev, field) = (vm.interns.get_str(prev), vm.interns.get_str(field));
        return Err(ExcType::type_error(format!(
            "non-default argument '{field}' follows default argument '{prev}'"
        )));
    }
    Ok(())
}

/// The first `(defaulted, non_defaulted)` field pair that would produce an
/// invalid `__init__` signature, or `None` when the order is valid.
fn first_non_default_after_default(fields: &[DataclassField]) -> Option<(StringId, StringId)> {
    let mut last_default = None;
    fields
        .iter()
        .find_map(|field| match (field.default.is_some(), last_default) {
            (true, _) => {
                last_default = Some(field.name);
                None
            }
            (false, Some(prev)) => Some((prev, field.name)),
            (false, None) => None,
        })
}

/// Whether a stringized annotation denotes `typing.ClassVar`, so the field is
/// excluded.
///
/// Detection is textual, where CPython resolves a string annotation through the
/// defining module's namespace. It therefore neither checks that `ClassVar` is
/// imported nor which module a dotted spelling refers to — both divergences are
/// recorded in `limitations/dataclasses.md`.
fn is_classvar(annotation: &str) -> bool {
    annotation_head(annotation, "ClassVar")
}

/// Whether a stringized annotation denotes `dataclasses.InitVar`. Matched the
/// same way as [`is_classvar`], and with the same textual-only caveats.
fn is_initvar(annotation: &str) -> bool {
    annotation_head(annotation, "InitVar")
}

/// Whether a stringized annotation names `name`, bare, subscripted, or
/// dotted (`typing.ClassVar[int]`), ignoring surrounding whitespace and quotes.
///
/// Quotes must be stripped because a quoted annotation (`x: "ClassVar[int]"`)
/// is stringized with its quotes intact. The subscript is split off before the
/// qualifier check so a dotted type argument (`ClassVar[a.b]`) still matches.
fn annotation_head(annotation: &str, name: &str) -> bool {
    let s = annotation.trim().trim_matches(|c| c == '\'' || c == '"').trim();
    let head = s.split_once('[').map_or(s, |(head, _)| head).trim_end();
    head.rsplit('.').next() == Some(name)
}

/// Dataclass field names in definition order, or `None` for a plain class —
/// the `Some`/`None` split the generic `Instance` code branches on.
pub(crate) fn dataclass_fields(class_id: HeapId, vm: &VM<'_>) -> Option<Vec<StringId>> {
    match vm.heap.get(class_id) {
        HeapData::Class(class) => class
            .dataclass_meta()
            .map(|meta| meta.fields.iter().map(|f| f.name).collect()),
        _ => None,
    }
}

/// Whether `class_id` names a dataclass, when the field names aren't needed.
pub(crate) fn is_dataclass_class(class_id: HeapId, vm: &VM<'_>) -> bool {
    matches!(vm.heap.get(class_id), HeapData::Class(c) if c.dataclass_meta().is_some())
}

/// Constructs a dataclass instance by binding `args` to the recorded fields.
///
/// No bytecode is generated: arguments bind natively as CPython's synthesized
/// `__init__(self, f1, f2=default, ...)` would, with defaults read from the class
/// namespace. Called from `instantiate_class`; drops the instance on error.
pub(crate) fn dataclass_init(
    vm: &mut VM<'_>,
    class_id: HeapId,
    instance_id: HeapId,
    args: ArgValues,
) -> Result<CallResult, RunError> {
    // Owned field metadata (name + has-default), releasing the heap borrow.
    let fields: Vec<(StringId, bool)> = match vm.heap.get(class_id) {
        HeapData::Class(class) => class
            .dataclass_meta()
            .expect("dataclass_init requires dataclass metadata")
            .fields
            .iter()
            .map(|f| (f.name, f.default.is_some()))
            .collect(),
        _ => unreachable!("dataclass_init called on a non-class"),
    };

    let values = match bind_dataclass_fields(vm, class_id, &fields, args) {
        Ok(values) => values,
        Err(e) => {
            Value::Ref(instance_id).drop_with(vm);
            return Err(e);
        }
    };

    // Store each bound value on the instance `__dict__`. On the rare set
    // failure (resource limit) drop the untouched tail and the instance.
    let mut values = values;
    for i in 0..values.len() {
        let value = mem::replace(&mut values[i], Value::None);
        let name = Value::InternString(fields[i].0);
        let set_result = if let HeapReadOutput::Instance(mut instance) = vm.heap.read(instance_id) {
            instance.set_attr(name, value, vm)
        } else {
            value.drop_with(vm);
            Ok(None)
        };
        match set_result {
            Ok(old) => old.drop_with(vm),
            Err(e) => {
                for v in values.drain(i + 1..) {
                    v.drop_with(vm);
                }
                Value::Ref(instance_id).drop_with(vm);
                return Err(e);
            }
        }
    }

    Ok(CallResult::Value(Value::Ref(instance_id)))
}

/// Binds `args` to one value per dataclass field, in field order.
///
/// The first error is recorded and the remaining arguments still drained, so no
/// path leaks a refcount. The instance is untouched; the caller owns it.
///
/// TODO(dataclass-keywords): a third binder alongside `args::bind_native` and
/// `args::bind_python`, all three reproducing the same CPython error wording and
/// able to drift. Fold into `Signature::bind` when the `@dataclass(...)` keyword
/// form lands — not a drop-in, as that fills a `&mut Vec<Value>` from `&[Value]`
/// defaults where this needs owned values and lazy namespace lookup.
fn bind_dataclass_fields(
    vm: &mut VM<'_>,
    class_id: HeapId,
    fields: &[(StringId, bool)],
    args: ArgValues,
) -> Result<Vec<Value>, RunError> {
    let n_fields = fields.len();
    let init_name = format!("{}.__init__", class_name(class_id, vm.heap, vm.interns));

    let (pos_iter, kwargs) = args.into_parts();
    let positionals: Vec<Value> = pos_iter.collect();
    let n_pos = positionals.len();

    // Materialize keyword pairs (name string + value); drop the key `Value`s.
    // A non-string key outranks every arity error below — CPython raises it from
    // the call machinery — but the mapping is drained first so nothing leaks.
    let mut keywords: Vec<(String, Value)> = Vec::with_capacity(kwargs.len());
    let mut nonstring_key = false;
    for (key, value) in kwargs {
        if let Some(name) = key.as_either_str(vm.heap) {
            let name = name.as_str(vm.interns).to_owned();
            key.drop_with(vm);
            keywords.push((name, value));
        } else {
            key.drop_with(vm);
            value.drop_with(vm);
            nonstring_key = true;
        }
    }

    if nonstring_key {
        for v in positionals {
            v.drop_with(vm);
        }
        for (_, v) in keywords {
            v.drop_with(vm);
        }
        return Err(ExcType::type_error_kwargs_nonstring_key());
    }

    // Positional arguments fill the leftmost slots; keywords fill by name. A
    // positional beyond the last field is parked in `excess`, since CPython binds
    // keywords first: `P(1, 2, 3, y=4)` is "multiple values for argument 'y'".
    let mut values: Vec<Option<Value>> = (0..n_fields).map(|_| None).collect();
    let mut excess: Vec<Value> = Vec::new();
    for (slot, value) in positionals.into_iter().enumerate() {
        if slot < n_fields {
            values[slot] = Some(value);
        } else {
            excess.push(value);
        }
    }

    let mut error: Option<RunError> = None;
    for (name, value) in keywords {
        if error.is_some() {
            value.drop_with(vm);
            continue;
        }
        match fields.iter().position(|(id, _)| vm.interns.get_str(*id) == name) {
            Some(idx) if values[idx].is_none() => values[idx] = Some(value),
            Some(_) => {
                value.drop_with(vm);
                error = Some(ExcType::type_error_duplicate_arg(&init_name, &name));
            }
            None => {
                value.drop_with(vm);
                error = Some(ExcType::type_error_unexpected_keyword(&init_name, &name));
            }
        }
    }

    // Too many positionals (CPython counts `self`, so +1 each side), reported
    // only once keyword binding has had its say.
    if error.is_none() && n_pos > n_fields {
        let required = fields.iter().filter(|(_, has_default)| !has_default).count();
        error = Some(ExcType::type_error_too_many_positional_range(
            &init_name,
            1 + required,
            1 + n_fields,
            1 + n_pos,
            0,
        ));
    }

    // Fill unbound slots from the defaults captured at decoration time; collect
    // names of missing fields.
    if error.is_none() {
        let mut missing: Vec<String> = Vec::new();
        for (idx, (id, has_default)) in fields.iter().enumerate() {
            if values[idx].is_some() {
                continue;
            }
            if *has_default {
                let name_str = vm.interns.get_str(*id);
                let default = match vm.heap.get(class_id) {
                    HeapData::Class(class) => class
                        .dataclass_meta()
                        .and_then(|meta| meta.fields.get(idx))
                        .and_then(|field| field.default.as_ref())
                        .map(|v| v.clone_with_heap(vm.heap)),
                    _ => None,
                };
                match default {
                    Some(v) => values[idx] = Some(v),
                    None => missing.push(name_str.to_owned()),
                }
            } else {
                missing.push(vm.interns.get_str(*id).to_owned());
            }
        }
        if !missing.is_empty() {
            let refs: Vec<&str> = missing.iter().map(String::as_str).collect();
            error = Some(ExcType::type_error_missing_positional_with_names(&init_name, &refs));
        }
    }

    // Excess positionals are never bound, so release them on every path.
    for v in excess {
        v.drop_with(vm);
    }

    if let Some(e) = error {
        for v in values.into_iter().flatten() {
            v.drop_with(vm);
        }
        return Err(e);
    }
    Ok(values.into_iter().map(|v| v.expect("all fields bound")).collect())
}

/// Field-wise `__eq__`: equal only to the *same* dataclass with equal fields.
/// Any other operand is `NotImplemented` (`Ok(None)`), so the caller falls back
/// to identity.
///
/// Mirrors CPython 3.14's generated `self.a == other.a and self.b == other.b`:
/// left to right, stopping at the first unequal pair, each compared with the
/// `==` *operator* rather than container equality (so a field whose `__eq__`
/// always returns `False` makes two dataclasses unequal even when it is the
/// same object on both sides).
pub(crate) fn dataclass_eq<'h>(
    instance: &HeapRead<'h, Instance>,
    field_names: &[StringId],
    other: &Value,
    vm: &mut VM<'h>,
) -> RunResult<Option<bool>> {
    let class_id = instance.get(vm.heap).class();
    // Only the same dataclass type can be equal; otherwise NotImplemented.
    let Some(HeapReadOutput::Instance(other_inst)) = other.read_heap(vm) else {
        return Ok(None);
    };
    if other_inst.get(vm.heap).class() != class_id {
        return Ok(None);
    }
    for name_id in field_names {
        let field_name = vm.interns.get_str(*name_id).to_owned();
        let a = field_value(instance, class_id, &field_name, vm.heap, vm.interns);
        let b = field_value(&other_inst, class_id, &field_name, vm.heap, vm.interns);
        match (a, b) {
            (Some(a), Some(b)) => {
                defer_drop!(a, vm);
                defer_drop!(b, vm);
                if !a.py_eq_operator(b, vm)? {
                    return Ok(Some(false));
                }
            }
            (a, b) => {
                // The generated `__eq__` reads each field as an attribute, so one
                // that resolves nowhere raises rather than comparing unequal.
                if let Some(a) = a {
                    a.drop_with(vm);
                }
                if let Some(b) = b {
                    b.drop_with(vm);
                }
                let class_name = class_name(class_id, vm.heap, vm.interns).into_owned();
                return Err(ExcType::attribute_error(&class_name, &field_name));
            }
        }
    }
    Ok(Some(true))
}

/// Synthesized `__repr__`: `ClassName(f1=v1, ...)`. Formatting is shared with
/// the host-supplied `Dataclass` via [`write_dataclass_repr`] so the two cannot
/// drift.
pub(crate) fn dataclass_repr_fmt<'h>(
    instance: &HeapRead<'h, Instance>,
    field_names: &[StringId],
    f: &mut impl Write,
    vm: &mut VM<'h>,
    heap_ids: &mut LazyHeapSet,
) -> RunResult<()> {
    let class_id = instance.get(vm.heap).class();
    let name = class_name(class_id, vm.heap, vm.interns).to_string();
    // CPython's generated `__repr__` reads each field as an attribute, so one
    // that resolves nowhere raises. Checked up front so no partial repr is
    // emitted (the whole string is built before returning in CPython too).
    for name_id in field_names {
        let field_name = vm.interns.get_str(*name_id);
        if field_slot(instance, class_id, field_name, vm.heap, vm.interns).is_none() {
            return Err(ExcType::attribute_error(&name, field_name));
        }
    }
    write_dataclass_repr(f, &name, field_names.len(), vm, heap_ids, |i, heap, interns| {
        let field_name = interns.get_str(field_names[i]).to_owned();
        let value = field_value(instance, class_id, &field_name, heap, interns);
        (field_name, value)
    })
}

/// Reads a field the way the generated methods' attribute access does: the
/// instance `__dict__` first, then the class namespace.
///
/// The class fallback is what makes a defaulted field readable on an instance
/// whose (class-body) `__init__` never assigned it — the default lives on as a
/// class attribute, exactly as CPython's `self.x` finds it. `None` means neither
/// binds the name, which callers report as `AttributeError`.
///
/// Returns an owned clone; use [`field_slot`] for a presence check that takes no
/// reference.
fn field_value<'h>(
    instance: &HeapRead<'h, Instance>,
    class_id: HeapId,
    name: &str,
    heap: &HeapReader<'h>,
    interns: &Interns,
) -> Option<Value> {
    field_slot(instance, class_id, name, heap, interns).map(|v| v.clone_with_heap(heap))
}

/// Borrowing form of [`field_value`], for callers that only need to know whether
/// the field resolves at all.
fn field_slot<'v, 'h>(
    instance: &HeapRead<'h, Instance>,
    class_id: HeapId,
    name: &str,
    heap: &'v HeapReader<'h>,
    interns: &Interns,
) -> Option<&'v Value> {
    instance
        .get(heap)
        .attrs()
        .get_by_str(name, heap, interns)
        .or_else(|| match heap.get(class_id) {
            HeapData::Class(class) => class.namespace().get_by_str(name, heap, interns),
            _ => None,
        })
}

/// `is_dataclass(obj)` — true when `obj` is a dataclass **class** or an
/// **instance** of one (matching CPython, which accepts both).
fn is_dataclass(vm: &mut VM<'_>, args: ArgValues) -> RunResult<Value> {
    let arg = args.get_one_arg("is_dataclass", vm.heap)?;
    let result = match &arg {
        Value::Ref(id) => match vm.heap.get(*id) {
            HeapData::Class(class) => class.dataclass_meta().is_some(),
            HeapData::Instance(instance) => {
                let class_id = instance.class();
                matches!(vm.heap.get(class_id), HeapData::Class(class) if class.dataclass_meta().is_some())
            }
            _ => false,
        },
        _ => false,
    };
    arg.drop_with(vm);
    Ok(Value::Bool(result))
}
