/** Core module assets generated by Jco's explicit component instantiation mode. */
export const COMPONENT_MODULE_NAMES = [
  'monty.component.core.wasm',
  'monty.component.core2.wasm',
  'monty.component.core3.wasm',
  'monty.component.core4.wasm',
] as const
