"""
Generate `crates/monty/src/types/case_data.rs`: two-stage case-mapping tables in the style of CPython's
`unicodectype.c`, read from the running CPython so they share its Unicode version.

Every code point gets a record holding its full lower, upper, title and casefold mappings plus the
`Uppercase`, `Lowercase`, `Lt`, `Cased` and `Case_Ignorable` flags; identical records and identical
128-code-point blocks are shared. Run with `uv run scripts/gen_case_data.py`, then `make format-rs`.
"""

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).parent.parent / 'crates' / 'monty' / 'src' / 'types' / 'case_data.rs'

SHIFT = 7
EXTENDED = 1 << 30
UPPER, LOWER, TITLE, CASED, CASE_IGNORABLE = 1, 2, 4, 8, 16

Record = tuple[int, int, int, int, int]


def main() -> None:
    extended: list[str] = []
    extended_index: dict[str, int] = {}
    records: list[Record] = [(0, 0, 0, 0, 0)]
    record_index: dict[Record, int] = {records[0]: 0}
    per_cp: list[int] = []

    def mapping(c: str, mapped: str) -> int:
        if mapped == c:
            return 0
        if len(mapped) == 1:
            return ord(mapped) - ord(c)
        if mapped not in extended_index:
            extended_index[mapped] = len(extended)
            extended.append(mapped)
        return EXTENDED | extended_index[mapped]

    for cp in range(sys.maxunicode + 1):
        if 0xD800 <= cp <= 0xDFFF:
            per_cp.append(0)
            continue
        c = chr(cp)
        record = (
            mapping(c, c.lower()),
            mapping(c, c.upper()),
            mapping(c, c.title()),
            mapping(c, c.casefold()),
            flags(c),
        )
        if record not in record_index:
            record_index[record] = len(records)
            records.append(record)
        per_cp.append(record_index[record])

    # split into blocks of 2**SHIFT code points and share identical ones
    size = 1 << SHIFT
    blocks: list[tuple[int, ...]] = []
    block_index: dict[tuple[int, ...], int] = {}
    index1: list[int] = []
    for start in range(0, len(per_cp), size):
        block = tuple(per_cp[start : start + size])
        if block not in block_index:
            block_index[block] = len(blocks)
            blocks.append(block)
        index1.append(block_index[block])
    index2 = [r for block in blocks for r in block]

    py = '.'.join(map(str, sys.version_info[:2]))
    lines = [
        f'//! Generated by `scripts/gen_case_data.py` from CPython {py} (Unicode {unicodedata.unidata_version}); do not edit.',
        '//!',
        '//! Two-stage lookup: `INDEX1[cp >> SHIFT]` picks a block and `INDEX2[(block << SHIFT) | (cp & MASK)]` a',
        '//! record. A mapping is a delta added to the code point, or `EXTENDED | i` for `EXTENDED_CASE[i]`.',
        '',
        '/// Bits of a code point indexing within a block.',
        f'pub(super) const SHIFT: usize = {SHIFT};',
        '/// Set on a mapping that indexes `EXTENDED_CASE` instead of being a delta.',
        f'pub(super) const EXTENDED: i32 = {EXTENDED:_};',
        '/// `Uppercase` property.',
        f'pub(super) const UPPER: u8 = {UPPER};',
        '/// `Lowercase` property.',
        f'pub(super) const LOWER: u8 = {LOWER};',
        '/// General category `Lt`.',
        f'pub(super) const TITLE: u8 = {TITLE};',
        '/// `Cased` property.',
        f'pub(super) const CASED: u8 = {CASED};',
        '/// `Case_Ignorable` property.',
        f'pub(super) const CASE_IGNORABLE: u8 = {CASE_IGNORABLE};',
        '',
        '/// Case data shared by every code point with the same mappings and flags.',
        'pub(super) struct CaseRecord {',
        '    pub lower: i32,',
        '    pub upper: i32,',
        '    pub title: i32,',
        '    pub fold: i32,',
        '    pub flags: u8,',
        '}',
        '',
        'pub(super) static RECORDS: &[CaseRecord] = &[',
    ]
    for lower, upper, title, fold, flag in records:
        lines.append(
            f'    CaseRecord {{ lower: {lower:_}, upper: {upper:_}, title: {title:_}, fold: {fold:_}, flags: {flag} }},'
        )
    lines.append('];')
    lines.append('')
    lines.append('pub(super) static EXTENDED_CASE: &[&str] = &[')
    for mapped in extended:
        lines.append('    "' + ''.join(f'\\u{{{ord(ch):x}}}' for ch in mapped) + '",')
    lines.append('];')
    lines.append('')
    lines.append(f'pub(super) static INDEX1: &[{int_type(max(index1))}] = &[')
    lines.extend(wrap(index1))
    lines.append('];')
    lines.append('')
    lines.append(f'pub(super) static INDEX2: &[{int_type(max(index2))}] = &[')
    lines.extend(wrap(index2))
    lines.append('];')
    OUT.write_text('\n'.join(lines) + '\n')
    print(
        f'{len(records)} records, {len(extended)} extended mappings, {len(blocks)} blocks, '
        f'index1 {len(index1)}, index2 {len(index2)}'
    )


def flags(c: str) -> int:
    """Case property flags of a single character, read from CPython's own predicates and Final_Sigma handling."""
    f = 0
    if c.isupper():
        f |= UPPER
    if c.islower():
        f |= LOWER
    if c.istitle() and not c.isupper():  # for one character istitle() is Lt or Uppercase
        f |= TITLE
    if f:
        f |= CASED
    # `Σ` lowers to `ς` only when the run of Case_Ignorable characters after it ends in an uncased character
    # (or the string), so these two probes separate Case_Ignorable from cased and from other characters.
    after_cased = ('AΣ' + c + 'A').lower()[1] == 'σ'
    after_uncased = ('AΣ' + c + '1').lower()[1] == 'ς'
    if after_cased and after_uncased:
        f |= CASE_IGNORABLE
    return f


def int_type(max_value: int) -> str:
    return 'u8' if max_value < 256 else 'u16'


def wrap(values: list[int], per_line: int = 32) -> list[str]:
    return ['    ' + ', '.join(map(str, values[i : i + per_line])) + ',' for i in range(0, len(values), per_line)]


if __name__ == '__main__':
    main()
