"""
Generate `crates/monty/src/types/titlecase_data.rs`: every code point whose titlecase mapping
differs from its uppercase mapping, read from the running CPython, which must be the version
Monty targets so the table shares its Unicode version.

Run with `uv run scripts/gen_titlecase.py`, then `make format-rs`.
"""

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).parent.parent / 'crates' / 'monty' / 'src' / 'types' / 'titlecase_data.rs'


def main() -> None:
    rows: list[tuple[int, str]] = []
    for cp in range(sys.maxunicode + 1):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        c = chr(cp)
        if c.title() != c.upper():
            rows.append((cp, c.title()))
    py = '.'.join(map(str, sys.version_info[:2]))
    lines = [
        f'//! Generated by `scripts/gen_titlecase.py` from CPython {py} (Unicode {unicodedata.unidata_version}); do not edit.',
        '',
        '/// Code points whose titlecase mapping differs from their uppercase mapping, sorted by code point.',
        '///',
        '/// Rust has no titlecase data, so `str.title()` and `str.capitalize()` fall back to',
        '/// `char::to_uppercase` for every character not listed here.',
        'pub(super) static TITLECASE_EXCEPTIONS: &[(char, &str)] = &[',
    ]
    for cp, title in rows:
        mapped = ''.join(f'\\u{{{ord(ch):x}}}' for ch in title)
        lines.append(f'    (\'\\u{{{cp:x}}}\', "{mapped}"),')
    lines.append('];')
    OUT.write_text('\n'.join(lines) + '\n')
    print(f'wrote {len(rows)} rows to {OUT}')


if __name__ == '__main__':
    main()
