#!/usr/bin/env bash
# Generate type stubs for external_functions.py into stubs.pyi
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

cd "$SCRIPT_DIR"
uv run stubgen external_functions.py --include-docstrings -o "$TMPDIR"

{
    echo "# Auto-generated by stubgen.sh — do not edit manually"
    echo ""
    cat "$TMPDIR/external_functions.pyi"
} > stubs.pyi

echo "Generated stubs.pyi"
