// Gradle build script for the monty-kotlin JVM library.
//
// This project bundles:
//   - Generated UniFFI Kotlin bindings (src/main/kotlin/, not committed — generated by `make gen-kotlin-bindings`)
//   - Native shared libraries for each supported platform (src/main/resources/, not committed):
//       darwin-aarch64/libmonty_kotlin.dylib  — macOS ARM64
//       linux-x86-64/libmonty_kotlin.so       — Linux x86_64 (cross-compiled via cargo-zigbuild)
//
// JNA discovers the platform-appropriate native lib from the JAR at runtime using its
// standard resource prefix convention (`/{Platform.RESOURCE_PREFIX}/lib{name}.{ext}`).

plugins {
    kotlin("jvm") version "2.0.21"
    `maven-publish`
    signing
}

group = "TODO.set.group.before.publishing"
version = "0.0.0-SNAPSHOT" // TODO: sync with workspace version

repositories {
    mavenCentral()
}

dependencies {
    // JNA is part of the public API: consumers need it on the classpath at runtime.
    api("net.java.dev.jna:jna:5.14.0")
}

// Include native libs from src/main/resources in the JAR automatically (standard Gradle behaviour).
sourceSets {
    main {
        resources {
            srcDir("src/main/resources")
        }
    }
}

java {
    withSourcesJar()
    withJavadocJar()
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

kotlin {
    jvmToolchain(11)
}

// Maven publishing — fill in coordinates before publishing to Maven Central.
publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])

            groupId = project.group.toString()
            artifactId = "monty-kotlin" // TODO: confirm artifact ID
            version = project.version.toString()

            pom {
                name.set("monty-kotlin")
                description.set("Kotlin/JVM bindings for the Monty sandboxed Python interpreter")
                // TODO: fill in url, licenses, developers, scm before publishing
            }
        }
    }

    repositories {
        // Publish to local Maven repo for testing: `./gradlew publishToMavenLocal`
        mavenLocal()
        // TODO: add Maven Central / OSSRH repository config before publishing
    }
}

// Signing — required by Maven Central but left stubbed until keys are configured.
signing {
    // Sign only when publishing; skip during local dev builds.
    setRequired({ gradle.taskGraph.hasTask("publish") })
    sign(publishing.publications["mavenJava"])
}
